### ISSUE TITLE
Building on AIX

### ISSUE THREAD

**Issue by mauroballestra** [node-ffi-napi/node-ffi-napi#103]
As mentioned in the [ref-napi issues](https://github.com/node-ffi-napi/ref-napi/issues/48) I'm trying to use ffi-napi within a driver my company wrote.
I'm now trying to use this driver on AIX and after found a workaround for ref-napi I'm now getting a compile error on AIX:

`> ffi-napi@3.0.1 install /home/fctech/Mauro/test/node_modules/ffi-napi
> node-gyp-build

gmake: Entering directory '/home/fctech/Mauro/test/node_modules/ffi-napi/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
../deps/libffi/src/prep_cif.c:26:10: fatal error: ffi.h: No such file or directo                                                                                                 ry
 #include <ffi.h>
          ^~~~~~~
compilation terminated.
gmake: *** [deps/libffi/ffi.target.mk:125: Release/obj.target/ffi/deps/libffi/sr                                                                                                 c/prep_cif.o] Error 1
gmake: Leaving directory '/home/fctech/Mauro/test/node_modules/ffi-napi/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/fctech/Mauro/node-v14.15.0-aix-                                                                                                 ppc64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                                                 s.js:277:12)
gyp ERR! System AIX 7.1
gyp ERR! command "/home/fctech/Mauro/node-v14.15.0-aix-ppc64/bin/node" "/home/fc                                                                                                 tech/Mauro/node-v14.15.0-aix-ppc64/lib/node_modules/npm/node_modules/node-gyp/bi                                                                                                 n/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fctech/Mauro/test/node_modules/ffi-napi
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/fctech/Mauro/test                                                                                                 /package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@3.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi-napi@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                 ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fctech/.npm/_logs/2020-11-10T07_43_24_541Z-debug.log
`
Referring to [Readme.md](https://github.com/node-ffi-napi/node-ffi-napi#requirements) it seem that the installation of libffi is not required, is this expected?

However I've manually installed libffi 3.3 on my system, after a successful installation here is the error I get:
`> ffi-napi@3.0.1 install /home/fctech/Mauro/test/node_modules/ffi-napi
> node-gyp-build

gmake: Entering directory '/home/fctech/Mauro/test/node_modules/ffi-napi/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
In file included from ../deps/libffi/src/prep_cif.c:27:
../deps/libffi/include/ffi_common.h:17:10: fatal error: fficonfig.h: No such file or directory
 #include <fficonfig.h>
          ^~~~~~~~~~~~~
compilation terminated.
gmake: *** [deps/libffi/ffi.target.mk:125: Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
gmake: Leaving directory '/home/fctech/Mauro/test/node_modules/ffi-napi/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/fctech/Mauro/node-v14.15.0-aix-ppc64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System AIX 7.1
gyp ERR! command "/home/fctech/Mauro/node-v14.15.0-aix-ppc64/bin/node" "/home/fctech/Mauro/node-v14.15.0-aix-ppc64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fctech/Mauro/test/node_modules/ffi-napi
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/fctech/Mauro/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@3.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi-napi@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fctech/.npm/_logs/2020-11-10T08_02_22_897Z-debug.log`

Even if the libffi installation doesn't provide fficonfig.h I tried to copy the fficonfig.h found in my build area to the system include: even if I don't think it's correct, after doing this here is the error I get:
`> ffi-napi@3.0.1 install /home/fctech/Mauro/test/node_modules/ffi-napi
> node-gyp-build

gmake: Entering directory '/home/fctech/Mauro/test/node_modules/ffi-napi/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
../deps/libffi/src/java_raw_api.c: In function 'ffi_java_raw_call':
../deps/libffi/src/java_raw_api.c:299:3: warning: 'ffi_java_raw_to_ptrarray' is deprecated [-Wdeprecated-declarations]
   ffi_java_raw_to_ptrarray (cif, raw, avalue);
   ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../deps/libffi/src/java_raw_api.c:38:
/usr/include/ffi.h:297:6: note: declared here
 void ffi_java_raw_to_ptrarray (ffi_cif *cif, ffi_java_raw *raw, void **args) __attribute__((deprecated));
      ^~~~~~~~~~~~~~~~~~~~~~~~
../deps/libffi/src/java_raw_api.c: In function 'ffi_java_translate_args':
../deps/libffi/src/java_raw_api.c:310:3: warning: 'ffi_java_raw_size' is deprecated [-Wdeprecated-declarations]
   ffi_java_raw *raw = (ffi_java_raw*)alloca (ffi_java_raw_size (cif));
   ^~~~~~~~~~~~
In file included from ../deps/libffi/src/java_raw_api.c:38:
/usr/include/ffi.h:299:8: note: declared here
 size_t ffi_java_raw_size (ffi_cif *cif) __attribute__((deprecated));
        ^~~~~~~~~~~~~~~~~
../deps/libffi/src/java_raw_api.c:313:3: warning: 'ffi_java_ptrarray_to_raw' is deprecated [-Wdeprecated-declarations]
   ffi_java_ptrarray_to_raw (cif, avalue, raw);
   ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../deps/libffi/src/java_raw_api.c:38:
/usr/include/ffi.h:295:6: note: declared here
 void ffi_java_ptrarray_to_raw (ffi_cif *cif, void **args, ffi_java_raw *raw) __attribute__((deprecated));
      ^~~~~~~~~~~~~~~~~~~~~~~~
../deps/libffi/src/java_raw_api.c: In function 'ffi_prep_java_raw_closure':
../deps/libffi/src/java_raw_api.c:351:3: warning: 'ffi_prep_java_raw_closure_loc' is deprecated [-Wdeprecated-declarations]
   return ffi_prep_java_raw_closure_loc (cl, cif, fun, user_data, cl);
   ^~~~~~
In file included from ../deps/libffi/src/java_raw_api.c:38:
/usr/include/ffi.h:427:1: note: declared here
 ffi_prep_java_raw_closure_loc (ffi_java_raw_closure*,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
../deps/libffi/src/x86/ffi.c: In function 'ffi_prep_args':
../deps/libffi/src/x86/ffi.c:62:31: error: 'FFI_TYPE_MS_STRUCT' undeclared (first use in this function); did you mean 'FFI_TYPE_STRUCT'?
        || ecif->cif->flags == FFI_TYPE_MS_STRUCT)
                               ^~~~~~~~~~~~~~~~~~
                               FFI_TYPE_STRUCT
../deps/libffi/src/x86/ffi.c:62:31: note: each undeclared identifier is reported only once for each function it appears in
../deps/libffi/src/x86/ffi.c: In function 'ffi_prep_cif_machdep':
../deps/libffi/src/x86/ffi.c:262:24: error: 'FFI_TYPE_SMALL_STRUCT_1B' undeclared (first use in this function); did you mean 'FFI_V2_TYPE_SMALL_STRUCT'?
           cif->flags = FFI_TYPE_SMALL_STRUCT_1B; /* same as char size */
                        ^~~~~~~~~~~~~~~~~~~~~~~~
                        FFI_V2_TYPE_SMALL_STRUCT
../deps/libffi/src/x86/ffi.c:266:24: error: 'FFI_TYPE_SMALL_STRUCT_2B' undeclared (first use in this function); did you mean 'FFI_V2_TYPE_SMALL_STRUCT'?
           cif->flags = FFI_TYPE_SMALL_STRUCT_2B; /* same as short size */
                        ^~~~~~~~~~~~~~~~~~~~~~~~
                        FFI_V2_TYPE_SMALL_STRUCT
../deps/libffi/src/x86/ffi.c: In function 'ffi_call':
../deps/libffi/src/x86/ffi.c:359:28: error: 'FFI_TYPE_MS_STRUCT' undeclared (first use in this function); did you mean 'FFI_TYPE_STRUCT'?
           || cif->flags == FFI_TYPE_MS_STRUCT))
                            ^~~~~~~~~~~~~~~~~~
                            FFI_TYPE_STRUCT
../deps/libffi/src/x86/ffi.c:412:10: error: 'FFI_SYSV' undeclared (first use in this function); did you mean 'FFI_OK'?
     case FFI_SYSV:
          ^~~~~~~~
          FFI_OK
../deps/libffi/src/x86/ffi.c: In function 'ffi_prep_incoming_args_SYSV':
../deps/libffi/src/x86/ffi.c:525:25: error: 'FFI_TYPE_MS_STRUCT' undeclared (first use in this function); did you mean 'FFI_TYPE_STRUCT'?
        || cif->flags == FFI_TYPE_MS_STRUCT ) {
                         ^~~~~~~~~~~~~~~~~~
                         FFI_TYPE_STRUCT
../deps/libffi/src/x86/ffi.c: In function 'ffi_prep_closure_loc':
../deps/libffi/src/x86/ffi.c:665:19: error: 'FFI_SYSV' undeclared (first use in this function); did you mean 'FFI_OK'?
   if (cif->abi == FFI_SYSV)
                   ^~~~~~~~
                   FFI_OK
../deps/libffi/src/x86/ffi.c:594:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    unsigned int  __fun = (unsigned int)(FUN); \
                          ^
../deps/libffi/src/x86/ffi.c:667:7: note: in expansion of macro 'FFI_INIT_TRAMPOLINE'
       FFI_INIT_TRAMPOLINE (&closure->tramp[0],
       ^~~~~~~~~~~~~~~~~~~
../deps/libffi/src/x86/ffi.c:595:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    unsigned int  __ctx = (unsigned int)(CTX); \
                          ^
../deps/libffi/src/x86/ffi.c:667:7: note: in expansion of macro 'FFI_INIT_TRAMPOLINE'
       FFI_INIT_TRAMPOLINE (&closure->tramp[0],
       ^~~~~~~~~~~~~~~~~~~
../deps/libffi/src/x86/ffi.c: In function 'ffi_prep_raw_closure_loc':
../deps/libffi/src/x86/ffi.c:718:19: error: 'FFI_SYSV' undeclared (first use in this function); did you mean 'FFI_OK'?
   if (cif->abi != FFI_SYSV) {
                   ^~~~~~~~
                   FFI_OK
../deps/libffi/src/x86/ffi.c:594:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    unsigned int  __fun = (unsigned int)(FUN); \
                          ^
../deps/libffi/src/x86/ffi.c:740:3: note: in expansion of macro 'FFI_INIT_TRAMPOLINE'
   FFI_INIT_TRAMPOLINE (&closure->tramp[0], &ffi_closure_raw_SYSV,
   ^~~~~~~~~~~~~~~~~~~
../deps/libffi/src/x86/ffi.c:595:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    unsigned int  __ctx = (unsigned int)(CTX); \
                          ^
../deps/libffi/src/x86/ffi.c:740:3: note: in expansion of macro 'FFI_INIT_TRAMPOLINE'
   FFI_INIT_TRAMPOLINE (&closure->tramp[0], &ffi_closure_raw_SYSV,
   ^~~~~~~~~~~~~~~~~~~
../deps/libffi/src/x86/ffi.c: In function 'ffi_raw_call':
../deps/libffi/src/x86/ffi.c:782:28: error: 'FFI_TYPE_MS_STRUCT' undeclared (first use in this function); did you mean 'FFI_TYPE_STRUCT'?
           || cif->flags == FFI_TYPE_MS_STRUCT))
                            ^~~~~~~~~~~~~~~~~~
                            FFI_TYPE_STRUCT
../deps/libffi/src/x86/ffi.c:829:10: error: 'FFI_SYSV' undeclared (first use in this function); did you mean 'FFI_OK'?
     case FFI_SYSV:
          ^~~~~~~~
          FFI_OK
gmake: *** [deps/libffi/ffi.target.mk:125: Release/obj.target/ffi/deps/libffi/src/x86/ffi.o] Error 1
gmake: Leaving directory '/home/fctech/Mauro/test/node_modules/ffi-napi/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/fctech/Mauro/node-v14.15.0-aix-ppc64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System AIX 7.1
gyp ERR! command "/home/fctech/Mauro/node-v14.15.0-aix-ppc64/bin/node" "/home/fctech/Mauro/node-v14.15.0-aix-ppc64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fctech/Mauro/test/node_modules/ffi-napi
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/fctech/Mauro/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@3.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi-napi@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fctech/.npm/_logs/2020-11-10T08_06_23_727Z-debug.log
`
I see that AIX is not listed into the [supported platforms](https://github.com/node-ffi-napi/node-ffi-napi#requirements) but I was wondering if this issue can be easy fix to extend platforms compatibility.

As this a specific sources build issue I preferred to report in node-ffi-napi issues, please let me know if this is not the right place where to report this.

Thanks

**Comment by nicwhitts** [comment]
Did you ever find a fix for this?

**Comment by mauroballestra** [comment]
Unfortunately no. I've never found a fix for this: honestly I've never had time to check with the newest versions, unsure if it's worth trying.

**Comment by AlvaroRausell** [comment]
@addaleax Apologies if you are the wrong person to ping, I am also hitting this issue on AIX, and I was wondering if there is any ongoing effort to solve this.

**Comment by addaleax** [comment]
If this is solved at some point, it’s going to be solved by somebody with access to an AIX system and a PR from them.
