### ISSUE TITLE
Problem when linking a .so depending of another .so

### ISSUE THREAD

**Issue by Psycokwet** [node-ffi-napi/node-ffi-napi#109]
Hello ! I have been working on a wrapper for a library (bass library, un4seen), and realized that, although it works very well on windows, I get some issues on linux.

There is one base library, and other add-on that may use the base library. With the dll on window, I can charge the base, and then as much add-on as I want, on linux however, the first .so is loaded without issue, but the other .so, depending on the first, does not load when I want to load them, they throw error whenever they find reference to functions existing in the base .so. Here is my log : 

```
/home/elleylean/Documents/bassaudioTester/node_modules/ffi-napi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: /home/elleylean/Documents/bassaudioTester/node_modules/bassaudio-updated/lib/linux64/libtags.so: undefined symbol: BASS_ChannelGetTags
    at new DynamicLibrary (/home/elleylean/Documents/bassaudioTester/node_modules/ffi-napi/lib/dynamic_library.js:74:11)
    at Object.Library (/home/elleylean/Documents/bassaudioTester/node_modules/ffi-napi/lib/library.js:45:14)
    at new Bass (/home/elleylean/Documents/bassaudioTester/node_modules/bassaudio-updated/index.js:651:26)
    at Object.<anonymous> (/home/elleylean/Documents/bassaudioTester/index.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

```

BASS_ChannelGetTags is a function belonging in libbass.so, that I did load before libtags.so.

Exactly in the same way I loaded bass.dll before tags.dll for windows, it the same code.

Here is the loading code for bass : 

```javascript
  this.basslib = ffi.Library(basslibName, {
    BASS_Init: ["bool", ["int", "int", "int", "int", "int"]],
    BASS_GetVersion: ["int", []],
    BASS_StreamCreate: [
      "int",
      ["int", "int", "int", "pointer", ref.types.int64],
    ],
    BASS_StreamCreateFile: [
      "int",
      ["bool", "string", ref.types.int64, ref.types.int64, "int"],
    ],
    BASS_StreamCreateURL: [
      "int",
      ["string", "int", "int", "pointer", ref.types.void],
    ],
    BASS_ChannelPlay: ["bool", ["int", "bool"]],
    BASS_ChannelStop: ["bool", ["int"]],
    BASS_ChannelPause: ["bool", ["int"]],
    BASS_ChannelGetPosition: [ref.types.int64, ["int", "int"]],
    BASS_ChannelSetPosition: ["bool", ["int", ref.types.int64, "int"]],
    BASS_ChannelGetLength: [ref.types.int64, ["int", "int"]],

    BASS_ChannelBytes2Seconds: [ref.types.double, ["int", ref.types.int64]],
    BASS_ChannelSeconds2Bytes: [ref.types.int64, ["int", ref.types.double]],
    BASS_ChannelGetLevel: ["int", ["int"]],
    BASS_ChannelRemoveSync: ["bool", ["int", "int"]],
    BASS_ChannelIsActive: ["int", ["int"]],
    BASS_ChannelSetAttribute: ["bool", ["int", "int", "float"]],
    BASS_ChannelGetAttribute: ["bool", ["int", "int", floatPTR]],
    BASS_ChannelSetSync: [
      "int",
      ["int", "int", ref.types.int64, "pointer", ref.types.void],
    ],

    BASS_ChannelSlideAttribute: ["bool", ["long", "long", "float", "long"]],
    BASS_ChannelIsSliding: ["bool", ["long", "long"]],
    BASS_ChannelGetDevice: ["int", ["int"]],
    BASS_ChannelSetDevice: ["bool", ["long", "long"]],
    BASS_StreamFree: ["bool", ["int"]],
    BASS_SetDevice: ["bool", ["int"]],
    BASS_SetVolume: ["bool", ["float"]],
    BASS_Start: ["bool", []],
    BASS_Stop: ["bool", []],
    BASS_Pause: ["bool", []],
    BASS_GetInfo: ["bool", [infoPTR]],
    BASS_ErrorGetCode: ["int", []],
    BASS_Free: ["bool", []],
    BASS_GetCPU: ["float", []],
    BASS_GetDevice: ["int", []],
    BASS_GetDeviceInfo: ["bool", ["int", deviceInfoPTR]],
    // BASS_ChannelGetTags: ["string", ["int", "int"]],
    BASS_ChannelGetInfo: ["bool", ["int", chanInfoPTR]],
    BASS_SetConfig: ["bool", ["int", "int"]],
    BASS_GetConfig: ["int", ["int"]],
    BASS_Update: ["bool", ["int"]],
    BASS_ChannelUpdate: ["bool", ["int", "int"]],
    BASS_RecordFree: ["bool", []],
    BASS_RecordGetDevice: ["int", []],
    BASS_RecordGetDeviceInfo: ["bool", ["int", recinfoPTR]],
    BASS_RecordGetInfo: ["bool", [recinfoPTR]],
    BASS_RecordGetInput: ["int", ["int", "float"]],
    BASS_RecordGetInputName: ["string", ["int"]],
    BASS_RecordInit: ["bool", ["int"]],
    BASS_RecordSetDevice: ["bool", ["int"]],
    BASS_RecordSetInput: ["bool", ["int", "int", "float"]],
    BASS_RecordStart: [
      "int",
      ["int", "int", "long", "pointer", ref.types.void],
    ],
  });

```

As you can see, the function on which tags is dependant, is present.

The code to load tag is the folowing : 
```javacript
  this.basslibtags = ffi.Library(this.basstagslibName, {
    BASS_ChannelGetTags: ["string", ["int", "int"]],
    TAGS_GetVersion: ["int", []],
    TAGS_Read: ["string", ["int", "string"]],
    TAGS_ReadEx: ["string", ["int", "string", "int", "int"]],
    TAGS_SetUTF8: ["bool", ["bool"]],
    TAGS_GetLastErrorDesc: ["string", []],
  });  

```

Ths differents "libNames" variables, are the full pathnames of respectively bass, and tag, adapting the path if we are on windows, or linux.

You can see full context here : 
https://github.com/Psycokwet/bassaudio-updated
In index.js. The dll/so/ even dylib are included and will be used depending on the platform you are working.
A normal way to test it would be to have this code : 

```javascript
var bass = require("bassaudio-updated");
var basslib = new bass();

console.log(basslib.BASS_GetVersion()); // Show that bass have been loaded
basslib.EnableTags(true); //trying to load tags add-on 
basslib.EnableMixer(true); //trying to load mix add-on
basslib.EnableEncoder(true); //trying to load encoder add-on
```

It seems like a bug to me, since that works fine on windows, but maybe we have to do things differently on linux ? I didn't find it if we do.

**Comment by Psycokwet** [comment]
I found the issue, in the file lib/libarary.js, the line : 
```javascript
  const dl = new DynamicLibrary(libfile || null, RTLD_NOW);
``` 

should be replaced by

```javascript
  const dl = new DynamicLibrary(libfile || null, RTLD_NOW | DynamicLibrary.FLAGS.RTLD_GLOBAL)
``` 

In order to work with .so depending on other .so on linux.

My wrapper have been originally created by someone else, who used a shim to replace this line. Since the dl variable was originally a var dl, and not a const dl, the shim wasn't correctly working anymore. I thought it may interest you that this modification in code was doing great work on linux. (I don't actually quite understand everything, but I thought that I may not be the only one interested in that)

Have a great day !

**Comment by addaleax** [comment]
I guess the `Library` constructor could take an additional flags argument? Would that solve your use case here?

**Comment by Psycokwet** [comment]
Well, as long as I can specify that I need  DynamicLibrary.FLAGS.RTLD_GLOBAL for the dl object, I guess so. :) 

Or a way to specify another lib as a parent lib file for another? 

I don't know much about ffi-napi, so I don't know which would make the more sense in your work. :)

But thank your for replying that fast ! :)

**Comment by joelpurra** [comment]
@Psycokwet: you can also use `FFI.DynamicLibrary` directly, if you load it globally, then use `FFI.Library` with a `null` path. This works when one library accesses another. (Tested on Linux, macOS a few months ago.)

Something like this:

```javascript
const FFI = require("ffi-napi");

// NOTE: your library
const myLibraryPath = ...;
const flags = FFI.DynamicLibrary.FLAGS.RTLD_NOW | FFI.DynamicLibrary.FLAGS.RTLD_GLOBAL;
const myDynamicLibrary = new FFI.DynamicLibrary(myLibraryPath, flags);

const myLibrary = new FFI.Library(null, {
  // NOTE: your methods.
});

// Unload when done using myLibrary.
myDynamicLibrary.close();
```

**Comment by Psycokwet** [comment]
Thank you, that's good to know. :) And I'm glad @addaleax took it into account ! Thank you for your investment and this great lib. :) I look forward to the next update !
