### ISSUE TITLE
Installation fails on Windows 10 x64 (Node 10.9.0, Python 3.7.0)

### ISSUE THREAD

**Issue by reebr** [node-ffi-napi/node-ffi-napi#11]
I'm trying to install the lib using the information of README, but I'm getting the following error on installation: 
```
PS C:\Users\renan.gomes\Desktop\development\ffi-test> yarn add ffi-napi
yarn add v1.6.0
(node:7000) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⡀ ref-napi: using node@10.9.0 | win32 | x64
[-/2] ⢀ waiting...
[-/2] ⢀ waiting...
[-/2] ⢀ waiting...
error C:\Users\renan.gomes\Desktop\development\ffi-test\node_modules\ref-napi: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\renan.gomes\Desktop\development\ffi-test\node_modules\ref-napi
Output:
C:\Users\renan.gomes\Desktop\development\ffi-test\node_modules\ref-napi>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@10.9.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Program Files (x86)\Python37-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\renan.gomes\Desktop\development\ffi-test\node_modules\ref-napi
```
My Node Version:
```
PS C:\Users\renan.gomes\Desktop\development\ffi-test> node -v
v10.9.0
```
I see something about Python on error message, so here's my Python version too:
```
PS C:\Users\renan.gomes\Desktop\development\ffi-test> py --version
Python 3.7.0
```

**Comment by addaleax** [comment]
There’s a good chance you (also?) need Python 2 for compiling any Node.js addons.

If not, could you provide a debug log? I don’t know about `yarn` but `npm install` produces one for failed installs.

**Comment by reebr** [comment]
Thanks @addaleax, you're right.
I've installed Python 2.7.14 and run the command again, the problem's gone.
