### ISSUE TITLE
Issues with update regarding .so depending other .so

### ISSUE THREAD

**Issue by Psycokwet** [node-ffi-napi/node-ffi-napi#111]
Hello ! I could not reopen my previous issue : 
https://github.com/node-ffi-napi/node-ffi-napi/issues/109

So I made a new one.

I tried to use the update, but I could not figure how I was supposed to make it work now, I'm sorry. I tried multiple combination, I've looked at the example, but I always get error, so, I guess I'm not doing it well. Could you please tell me how I should do it ?

**Comment by addaleax** [comment]
What did you try and how did it fail? e.g. replacing `ffi.Library(basslibName, {` with `ffi.Library(new ffi.DynamicLibrary(basslibName, DynamicLibrary.FLAGS.RTLD_NOW | DynamicLibrary.FLAGS.RTLD_GLOBAL), {`?

**Comment by Psycokwet** [comment]
If I do that :
``` javascript

  this.basslib = ffi.Library(new ffi.DynamicLibrary(basslibName, ffi.DynamicLibrary.FLAGS.RTLD_NOW | ffi.DynamicLibrary.FLAGS.RTLD_GLOBAL),{

  // this.basslib = ffi.Library(basslibName, {
    BASS_Init: ["bool", ["int", "int", "int", "int", "int"]],
    BASS_GetVersion: ["int", []],
    BASS_StreamCreate: [
      "int",
      ["int", "int", "int", "pointer", ref.types.int64],
    ],
    BASS_StreamCreateFile: [
      "int",
      ["bool", "string", ref.types.int64, ref.types.int64, "int"],
    ],
    BASS_StreamCreateURL: [
      "int",
      ["string", "int", "int", "pointer", ref.types.void],
    ],
    BASS_ChannelPlay: ["bool", ["int", "bool"]],
    BASS_ChannelStop: ["bool", ["int"]],
    BASS_ChannelPause: ["bool", ["int"]],
    BASS_ChannelGetPosition: [ref.types.int64, ["int", "int"]],
    BASS_ChannelSetPosition: ["bool", ["int", ref.types.int64, "int"]],
    BASS_ChannelGetLength: [ref.types.int64, ["int", "int"]],

    BASS_ChannelBytes2Seconds: [ref.types.double, ["int", ref.types.int64]],
    BASS_ChannelSeconds2Bytes: [ref.types.int64, ["int", ref.types.double]],
    BASS_ChannelGetLevel: ["int", ["int"]],
    BASS_ChannelRemoveSync: ["bool", ["int", "int"]],
    BASS_ChannelIsActive: ["int", ["int"]],
    BASS_ChannelSetAttribute: ["bool", ["int", "int", "float"]],
    BASS_ChannelGetAttribute: ["bool", ["int", "int", floatPTR]],
    BASS_ChannelSetSync: [
      "int",
      ["int", "int", ref.types.int64, "pointer", ref.types.void],
    ],

    BASS_ChannelSlideAttribute: ["bool", ["long", "long", "float", "long"]],
    BASS_ChannelIsSliding: ["bool", ["long", "long"]],
    BASS_ChannelGetDevice: ["int", ["int"]],
    BASS_ChannelSetDevice: ["bool", ["long", "long"]],
    BASS_StreamFree: ["bool", ["int"]],
    BASS_SetDevice: ["bool", ["int"]],
    BASS_SetVolume: ["bool", ["float"]],
    BASS_Start: ["bool", []],
    BASS_Stop: ["bool", []],
    BASS_Pause: ["bool", []],
    BASS_GetInfo: ["bool", [infoPTR]],
    BASS_ErrorGetCode: ["int", []],
    BASS_Free: ["bool", []],
    BASS_GetCPU: ["float", []],
    BASS_GetDevice: ["int", []],
    BASS_GetDeviceInfo: ["bool", ["int", deviceInfoPTR]],
    BASS_ChannelGetTags: ["string", ["int", "int"]],
    BASS_ChannelGetInfo: ["bool", ["int", chanInfoPTR]],
    BASS_SetConfig: ["bool", ["int", "int"]],
    BASS_GetConfig: ["int", ["int"]],
    BASS_Update: ["bool", ["int"]],
    BASS_ChannelUpdate: ["bool", ["int", "int"]],
    BASS_RecordFree: ["bool", []],
    BASS_RecordGetDevice: ["int", []],
    BASS_RecordGetDeviceInfo: ["bool", ["int", recinfoPTR]],
    BASS_RecordGetInfo: ["bool", [recinfoPTR]],
    BASS_RecordGetInput: ["int", ["int", "float"]],
    BASS_RecordGetInputName: ["string", ["int"]],
    BASS_RecordInit: ["bool", ["int"]],
    BASS_RecordSetDevice: ["bool", ["int"]],
    BASS_RecordSetInput: ["bool", ["int", "int", "float"]],
    BASS_RecordStart: [
      "int",
      ["int", "int", "long", "pointer", ref.types.void],
    ],
  });
```

I get this : 
```


/home/elleylean/Documents/bassaudioTester/node_modules/ffi-napi/lib/library.js:37
  if (libfile && libfile.indexOf(EXT) === -1) {
                         ^

TypeError: libfile.indexOf is not a function
    at Object.Library (/home/elleylean/Documents/bassaudioTester/node_modules/ffi-napi/lib/library.js:37:26)
    at new Bass (/home/elleylean/Documents/bassaudioTester/node_modules/bassaudio-updated/index.js:579:22)
    at Object.<anonymous> (/home/elleylean/Documents/bassaudioTester/index.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```

I tried to add the flag I need at the end or the beginnig of ffi.Library call too, giving my this.basslib to this child library too. I tried giving "null" also as a first parameter, since I saw that in some examples, but I must have misinterpret what it is used for I guess.
For remainder, basslib is the parent lib

**Comment by Psycokwet** [comment]
(I tried this stuff on the parent lib and the childs libs too, but certainly in a messy way too, I wasn't so sure of how I should handle it, I tried reading the code, the examples, but was a bit lost)

**Comment by addaleax** [comment]
@Psycokwet That looks like you might not be using the latest version of ffi-napi?

**Comment by Psycokwet** [comment]
... Yes, it was, I'm sorry your solution works ! I was still testing in a bad test folder.

Thank you !
