### ISSUE TITLE
What kind of situation could cause this?

### ISSUE THREAD

**Issue by Psycokwet** [node-ffi-napi/node-ffi-napi#122]
Hello !
I'm at loss on this one ! 

I have successfully used ffi napi to use "libbass.so" and other lib files depending on this one (see https://github.com/Psycokwet/bassaudio-updated/tree/master/package/lib to see every ones I could successfully use).
Libbass.so is the "main lib", every other lib file I use depend on it.

``` javascript
ffi.Library(
    new ffi.DynamicLibrary(
      libbass.so,
      ffi.DynamicLibrary.FLAGS.RTLD_NOW | ffi.DynamicLibrary.FLAGS.RTLD_GLOBAL
    ), ffiFunDeclaration)
```

And, I have been trying to set the basis to allow people to use other libs files from http://www.un4seen.com/ related to the ones I have set in my wrapper.
I have tested my code with two new files : libbassflac.so and libbasswebm.so (I even tried with tags.so, as if it wasn"t already included on my wrapper)

If libbasswebm and tags seems to be working fine on my work in progress to allow to add new lib files from the user, I have an issue when testing with libbassflac specifically. I get the following error log :

```
libbass.so: cannot open shared object file: No such file or directory
internal/fs/utils.js:259
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'libbass.so'
    at Object.openSync (fs.js:461:3)
    at readFileSync (fs.js:364:35)
    at new DynamicLibrary (/home/me/Documents/npm-depots/bassaudio-updated/node_modules/ffi-napi/lib/dynamic_library.js:79:23)
    at Object.Library (/home/me/Documents/npm-depots/bassaudio-updated/node_modules/ffi-napi/lib/library.js:47:10)
    at enableLibInt (/home/me/Documents/npm-depots/bassaudio-updated/package/enableLibInt.js:12:22)
    at enableLib (/home/me/Documents/npm-depots/bassaudio-updated/package/setters/setEnableLibs.js:36:5)
    at Bass.bass.<computed> [as EnableFlac] (/home/me/Documents/npm-depots/bassaudio-updated/package/setters/setEnableLibs.js:25:38)
    at Object.<anonymous> (/home/me/Documents/npm-depots/bassaudio-updated/tests/addFun.test.js:61:9)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'libbass.so'
}
```

I have tried to find where I would have set the wrong path by mistake, but, tracking until DynamicLibrary function itself, right before it determine the error, I could only find the right path, not the wrong one. Why would it try to open libbass.so suddenly? When other lib file depending on it as well didn't try to do it (or at least didn't fail doing so), everywhere on logs I can see that I am trying to open libbassflac.so, but the error is on libbass.so, how is it possible?

Thank you for your time, and I wish you the best on this end of the year !

**Comment by addaleax** [comment]
I think you might need to share a little more code in order for me to be able to help you … and, in particular, which version of ffi-napi are you using here?

**Comment by addaleax** [comment]
I think you might need to share a little more code in order for me to be able to help you … and, in particular, which version of ffi-napi are you using here?

**Comment by Psycokwet** [comment]
Apparently I'm using the latest version ffi-napi@3.1.0
Sorry for the absence of code, I thought that may be something obvious I was missing. Here is a full example :
https://github.com/Psycokwet/blob

Let me know if there is another issue on your side, the output I get here is :
```
me@x1xtrem:~/Documents/blob$ node ffi-napi-test.js 
trying to set webm
Successfully set webm
trying to set tags
Successfully set tags
trying to set flac
/home/me/Documents/blob/node_modules/ffi-napi/lib/dynamic_library.js:75
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: libbass.so: cannot open shared object file: No such file or directory
    at new DynamicLibrary (/home/me/Documents/blob/node_modules/ffi-napi/lib/dynamic_library.js:75:11)
    at Object.Library (/home/me/Documents/blob/node_modules/ffi-napi/lib/library.js:47:10)
    at minimalBass (/home/me/Documents/blob/ffi-napi-test.js:90:9)
    at Object.<anonymous> (/home/me/Documents/blob/ffi-napi-test.js:98:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by addaleax** [comment]
Okay, I see – I think the problem might be that, unlike Windows, the dynamic linker on Linux (assuming that that’s what you’re using) doesn’t automatically load files from the current working directory. If you look at the file you’re trying to load, you’ll see that it depends on `libbass.so`:

```
$ ldd libbassflac.so
	linux-vdso.so.1 (0x00007ffd5e54e000)
	libbass.so => not found # <------ HERE
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa9a1d18000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa9a1927000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa9a22c5000)
```

You may be able to fix this by loading `libbass.so` first, or, if that does not work, setting the `LD_LIBRARY_PATH` environment variable (the [man page for ld.so has more details](https://linux.die.net/man/8/ld.so)).

**Comment by Psycokwet** [comment]
It's already the case, libbass.so is the first one to be loaded, or maybe I do not quite get what you are saying by that?

Tags and webm also depend ob libbass, and I have other files that does too.
I don't know why flac has issues while the other files don't, when they all depend on libbass.so :o

Yes, I'm using linux right now !

I tried ldd with each files I have been using until now :
```
me@x1xtrem:~/Documents/blob$ ldd libtags.so 
	linux-vdso.so.1 (0x00007ffe68d53000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff67f5ae000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff67f593000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff67f3a1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff67f252000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff67f9b4000)
me@x1xtrem:~/Documents/blob$ ldd libbass.so 
	linux-vdso.so.1 (0x00007fff5f5a4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fccb704f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fccb702c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fccb7021000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fccb6ed2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fccb6ce0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fccb72c6000)
me@x1xtrem:~/Documents/blob$ ldd libbasswebm.so 
	linux-vdso.so.1 (0x00007ffddc7d1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fec1beb1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fec1c2c4000)
me@x1xtrem:~/Documents/blob$ ldd libbassflac.so 
	linux-vdso.so.1 (0x00007fff391f5000)
	libbass.so => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f21c1ba2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f21c19b0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f21c1f18000)
me@x1xtrem:~/Documents/blob$ ldd libbassmix.so 
	linux-vdso.so.1 (0x00007ffc88847000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f00f4979000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f00f482a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f00f4638000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f00f4bbe000)
me@x1xtrem:~/Documents/blob$ ldd libbassenc.so 
	linux-vdso.so.1 (0x00007fff1019d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fba5af1e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fba5af13000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fba5ad21000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fba5b163000)

```

I see that only libflac appear to be dependent on libbass.so with that command, but that not true :o I guess that may be an issue on the library side maybe? 

Previously I even openned an issue to ask for a way to set a "parent dependency",  on https://github.com/node-ffi-napi/node-ffi-napi/issues?q=psycokwet

Because when I was trying to load libbassenc and libbassmix, it  wasn't working *because* they depend on libbass.so. So I'm pretty sure about the fact that libbassflac is no exception in this.

What do you think? :o
