### ISSUE TITLE
Problem on mac to load certain dylib

### ISSUE THREAD

**Issue by Psycokwet** [node-ffi-napi/node-ffi-napi#123]
Hello again ! 

I am getting this result on mac : 

```
    Dynamic Linking Error: dlopen(/Users/me/Documents/npm-depots/bassaudio-updated/tests/basswebm24-osx/libbasswebm.dylib, 2): Library not loaded: @loader_path/libbass.dylib
      Referenced from: /Users/me/Documents/npm-depots/bassaudio-updated/tests/basswebm24-osx/libbasswebm.dylib
      Reason: image not found

       6 | 
       7 | function enableLibInt(bass, libFile, pathOrDl, ffiFunDeclaration) {
    >  8 |   libFile.enable(ffi.Library(pathOrDl, ffiFunDeclaration));
         |                      ^
       9 | 
      10 |   for (let fun in ffiFunDeclaration) {
      11 |     bass[fun] = (...args) => libFile.tryFunc(fun, ...args);

      at new DynamicLibrary (node_modules/ffi-napi/lib/dynamic_library.js:75:11)
      at Object.Library (node_modules/ffi-napi/lib/library.js:47:10)
      at enableLibInt (package/enableLibInt.js:8:22)
      at enableLib (package/setters/setEnableLibs.js:32:5)
      at Bass.EnableWebm (package/setters/setEnableLibs.js:22:38)
      at Object.<anonymous> (tests/addFun.test.js:29:9)
```

here is otool result to the faulty file
```
me@MacBook-Pro bassaudio-updated % otool -L  tests/basswebm24-osx/libbasswebm.dylib 
tests/basswebm24-osx/libbasswebm.dylib:
	@loader_path/libbasswebm.dylib (compatibility version 1.0.0, current version 1.0.0)
	@loader_path/libbass.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

and here are the result from some that are working. I don't quite see what may be faulty in libbasswebm.dylib regarding those.
```
me@MacBook-Pro bassaudio-updated % otool -L  package/lib/macOs/libbassmix.dylib 
package/lib/macOs/libbassmix.dylib:
	@loader_path/libbassmix.dylib (compatibility version 1.0.0, current version 1.0.0)
	@loader_path/libbass.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 822.31.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
me@MacBook-Pro bassaudio-updated % otool -L  package/lib/macOs/libtags.dylib 
package/lib/macOs/libtags.dylib:
	@loader_path/libtags.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0, weak)
	@loader_path/libbass.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 60.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 2577.0.0)
```

I just got a doubt, and tried putting this file in the same folder than the other files, and it suddenly worked. Since it was the only one that wasn't in the same folder as the other dylib.
Would there be a way to allow to load a file, depending on another, if they are not in the same folder both of them?
It works fine on windows and linux, it's only on mac that I'm getting this issue for now.

**Comment by rodchen-king** [comment]
@Psycokwet Have you solved the problem？I have the same issue now.
