### ISSUE TITLE
Incompatible with worker_threads

### ISSUE THREAD

**Issue by splitice** [node-ffi-napi/node-ffi-napi#125]
As per #121

1. Requring node-ffi from within a worker thread myself results in a segfault when closing the thread at end of work as well.

```
#0  0x00007ffff402d870 in ?? ()
#1  0x0000000001444de5 in uv__finish_close (handle=0x7fffc802f560) at ../deps/uv/src/unix/core.c:303
#2  uv__run_closing_handles (loop=0x7fffdeffcad8) at ../deps/uv/src/unix/core.c:317
#3  uv_run (loop=0x7fffdeffcad8, mode=UV_RUN_ONCE) at ../deps/uv/src/unix/core.c:395
#4  0x0000000000b2629d in node::worker::Worker::Run() ()
#5  0x0000000000b26908 in node::worker::Worker::StartThread(v8::FunctionCallbackInfo<v8::Value> const&)::{lambda(void*)#1}::_FUN(void*) ()
#6  0x00007ffff7c87fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007ffff7bb84cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

2. Also if you initialize node-ffi in multiple worker threads, or in the main thread in addition to the worker thread you will get a segfault as well.

```
#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7fc568bf1fb0
 1: 0xad13f1  [node]
 2: 0x1aad784 V8_Fatal(char const*, ...) [node]
 3: 0xf29cb9 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xc690f8 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0xa1f820 napi_get_typedarray_info [node]
 6: 0x7fc5685e946a  [/home/splitice/x4bflow/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node]
 7: 0x7fc5685e9d2d  [/home/splitice/x4bflow/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node]
 8: 0x7fc570145203 FFI::WrapPointerImpl(Napi::Env, char*, unsigned long) [/home/splitice/x4bflow/node_modules/ffi-napi/build/Release/ffi_bindings.node]
 9: 0x7fc570147b1b FFI::FFI::InitializeBindings(Napi::Env, Napi::Object) [/home/splitice/x4bflow/node_modules/ffi-napi/build/Release/ffi_bindings.node]
10: 0x7fc570149083 FFI::InitializeBindings(Napi::CallbackInfo const&) [/home/splitice/x4bflow/node_modules/ffi-napi/build/Release/ffi_bindings.node]
11: 0x7fc570149d83 Napi::details::CallbackData<Napi::Value (*)(Napi::CallbackInfo const&), Napi::Value>::Wrapper(napi_env__*, napi_callback_info__*) [/home/splitice/x4bflow/node_modules/ffi-napi/build/Release/ffi_bindings.node]
12: 0xa16bdf  [node]
13: 0xca831b  [node]
14: 0xca98cc  [node]
15: 0xca9f46 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
16: 0x14c8019  [node]
Illegal instruction
```

**Comment by addaleax** [comment]
Yeah, thanks for opening this – not sure why the original issue was closed :+1:

That being said, it’s probably still going to take a bit until I can get to this

**Comment by Morritz** [comment]
I also experienced that problem.

**Comment by KishanBagaria** [comment]
Just flagging this happens with node v16 as well and isn't isolated to Electron.

Repro steps:

1. Make a new directory and cd into it.
2. 
```sh
npm i ffi-napi
node -e 'const {Worker}=require("worker_threads"); new Worker(`require("ffi-napi")`, {eval:true})'
```
3. Will result in a seg fault: <img width="904" alt="" src="https://user-images.githubusercontent.com/1093313/118353722-3c302c80-b585-11eb-8112-6eb8ed064a5f.png">

**Comment by Vict0r-Chen** [comment]
I found this problem in Electron v11.3.0 and solved it after I upgraded to v13.1.2

**Comment by Morritz** [comment]
> I found this problem in Electron v11.3.0 and solved it after I upgraded to v13.1.2

What is the node version?

**Comment by lutangar** [comment]
Adding more feedbacks on nodejs versions on which the problem occurs :
> borrowing @KishanBagaria examples :

```shell
# nodejs v12.22.7
node -e 'const {Worker}=require("worker_threads"); new Worker(`require("ffi-napi")`, {eval:true})'
# [1]    1058630 segmentation fault (core dumped)  node -e 
node -e 'require("ffi-napi");const {Worker}=require("worker_threads"); new Worker(`require("ffi-napi")`, {eval:true})'
# ✓
```

```shell
# nodejs v13.14.0
node -e 'const {Worker}=require("worker_threads"); new Worker(`require("ffi-napi")`, {eval:true})'                    
# [1]    1054820 segmentation fault (core dumped)  node -e 
node -e 'require("ffi-napi");const {Worker}=require("worker_threads"); new Worker(`require("ffi-napi")`, {eval:true})'
# ✓
```

```shell
# nodejs v14.18.2
node -e 'const {Worker}=require("worker_threads"); new Worker(`require("ffi-napi")`, {eval:true})'
# [1]    1056440 segmentation fault (core dumped)  node -e 
node -e 'require("ffi-napi");const {Worker}=require("worker_threads"); new Worker(`require("ffi-napi")`, {eval:true})'
#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7f0eaede3700
 1: 0xaa6321  [node]
 2: 0x1a3b584 V8_Fatal(char const*, ...) [node]
 3: 0xe9afd9 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xbe4c38 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0x9f1c70 napi_get_typedarray_info [node]
 6: 0x7f0eaedef566  [node_modules/ref-napi/prebuilds/linux-x64/node.napi.node]
 7: 0x7f0eaedefdad  [node_modules/ref-napi/prebuilds/linux-x64/node.napi.node]
 8: 0x7f0eb4020cd7 FFI::WrapPointerImpl(Napi::Env, char*, unsigned long) [node_modules/ffi-napi/build/Release/ffi_bindings.node]
 9: 0x7f0eb402297d FFI::FFI::InitializeBindings(Napi::Env, Napi::Object) [node_modules/ffi-napi/build/Release/ffi_bindings.node]
10: 0x7f0eb402368b FFI::InitializeBindings(Napi::CallbackInfo const&) [node_modules/ffi-napi/build/Release/ffi_bindings.node]
11: 0x7f0eb402461b Napi::details::CallbackData<Napi::Value (*)(Napi::CallbackInfo const&), Napi::Value>::Wrapper(napi_env__*, napi_callback_info__*) [node_modules/ffi-napi/build/Release/ffi_bindings.node]
12: 0x9e8a7d  [node]
13: 0xc238db  [node]
14: 0xc24e86  [node]
15: 0xc25506 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
16: 0x1446459  [node]
[1]    1056477 illegal hardware instruction (core dumped)  node -e 
```

### Summary
> Requring node-ffi from within a worker thread myself results in a `segfault` when closing the thread at end of work as well.

Since nodejs v12.22.7 and probably on previous versions.

> Also if you initialize node-ffi in multiple worker threads, or in the main thread in addition to the worker thread you will get a segfault as well.

Since nodejs v14.18.2 and up.
