### ISSUE TITLE
node-gyp-build failing for arm64v8/musl (alpine)

### ISSUE THREAD

**Issue by klutchell** [node-ffi-napi/node-ffi-napi#126]
As the title says, I'm having trouble installing on alpine for arm64.

Here's an example dockerfile:

```dockerfile
FROM arm64v8/node:12-alpine

RUN apk update && apk add --no-cache -t .build-deps \
        libstdc++ \
        binutils-gold \
        curl \
        g++ \
        gcc \
        gnupg \
        libgcc \
        linux-headers \
        make \
        python3 \
        git \
        openssh \
        bash && \
    npm install ffi-napi && \
    apk del --purge .build-deps
```

Here are the build logs from that dockerfile:

```plaintext
> ref-napi@2.1.2 install /node_modules/ref-napi
> node-gyp-build

make: Entering directory '/node_modules/ref-napi/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/node_modules/ref-napi/build'

> ffi-napi@3.1.0 install /node_modules/ffi-napi
> node-gyp-build

make: Entering directory '/node_modules/ffi-napi/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/aarch64/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/aarch64/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  SOLINK_MODULE(target) Release/obj.target/ffi_bindings.node
/usr/lib/gcc/aarch64-alpine-linux-musl/9.3.0/../../../../aarch64-alpine-linux-musl/bin/ld: Release/obj.target/deps/libffi/libffi.a(ffi.o): in function `ffi_prep_closure_loc':
ffi.c:(.text+0xb60): undefined reference to `ffi_data_to_code_pointer'
/usr/lib/gcc/aarch64-alpine-linux-musl/9.3.0/../../../../aarch64-alpine-linux-musl/bin/ld: Release/obj.target/ffi_bindings.node: hidden symbol `ffi_data_to_code_pointer' isn't defined
/usr/lib/gcc/aarch64-alpine-linux-musl/9.3.0/../../../../aarch64-alpine-linux-musl/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [ffi_bindings.target.mk:150: Release/obj.target/ffi_bindings.node] Error 1
make: Leaving directory '/node_modules/ffi-napi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.8.0-7630-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/ffi-napi
gyp ERR! node -v v12.20.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@3.1.0 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi-napi@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-04T18_50_47_316Z-debug.log
```

I've also tried with Node 14 and had the same result. Is there a workaround or is this a known issue with musl?

**Comment by EwoutH** [comment]
Same issue, currently blocks our Arm64 builds

**Comment by maaelphd** [comment]
I'm getting some error i think it's correlationed to node-gyp too
I've tried with node js 14, 12, 10. tried using x86 or 64bits for all versions, i tried change python path, for some differents versions too like 2.7, 3.8 e 3.9 with differents architecture, even using microsoft store to install python, how tell the node-gyp instructions. I followed the instructions to use correctaly node-gyp, installing windows build tools 2017 an activate the "Visual C++ build tools" workload change python path with 'npm config' to C:\PythonXX, also change msvs_version to 2017. I really don't know if is a problem with ffi-napi or node-gyp. At some momment on my project, this addon was working fine but i needed change my node from 64Bits to x86, when i removed and install x86 node, this problems come out, and isin't working anymore. now i'm using nodeJs: v10.15.3, node-gyp: v5.1.0
and tried install ffi-napi@3.0.1. i'm get theses erros:

```
> D:\Codigo\npm\teste_ffi>npm install ffi-napi@3.0.1

> ref-napi@2.1.2 install D:\Codigo\npm\teste_ffi\node_modules\ref-napi
> node-gyp-build

> ffi-napi@3.0.1 install D:\Codigo\npm\teste_ffi\node_modules\ffi-napi
> node-gyp-build

D:\Codigo\npm\teste_ffi\node_modules\ffi-napi>if not defined npm_config_node_gyp (node "C:\Users\MYUSER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\MYUSER\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: EPERM: operation not permitted, read
gyp ERR! stack     at Object.readSync (fs.js:493:3)
gyp ERR! stack     at tryReadSync (fs.js:332:20)
gyp ERR! stack     at Object.readFileSync (fs.js:361:19)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:20)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:600:32)
gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:637:17)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:22:18)
gyp ERR! stack     at Object.<anonymous> (C:\Users\MYUSER\AppData\Roaming\npm\node_modules\npm\node_modules\request\index.js:18:15)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\MYUSER\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Codigo\npm\teste_ffi\node_modules\ffi-napi
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN teste_ffi@1.0.0 No description
npm WARN teste_ffi@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! ffi-napi@3.0.1 install: `node-gyp-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the ffi-napi@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MYUSER\AppData\Roaming\npm-cache\_logs\2021-02-27T06_13_38_012Z-debug.log
```

**Comment by MiLaDTechS** [comment]
@maaelphd i have the same problem, did you managed to solve it ? if yes can you please share ?

**Comment by maaelphd** [comment]
> @maaelphd i have the exact same problem and did almost everything you did too, did you managed to solve it ? if yes can you please share ?

Hey man, sorry to take to loong to respond.
I've solved it, has i can remember first of all i uninstalled all programs, node, vs build tools, npm, python, and delete all folder on %appdata% associated to node. So i install npm 14.16.1, and you need to install Visual Studio Community 2019, this works for me, i've tryed "vs build tools 2017" but i could not make this work with this version.
On Workloads i checked the Python Development, Node.js Development, and C++ development for desktop. Also in "Individual components" tab, i have to check for some thes. Here's a print from all i have checked. It's in Portuguese Br, just translate if you don't find. Some thes come already checked after you install vs community.
![msCOmmunit](https://user-images.githubusercontent.com/21028643/125328441-b0cfdf00-e31a-11eb-94b1-252a440c0ddb.png)


I also set python path with "C:\Python39\python.exe", as you can see i used python v39

And i maked all necessary configurations.
"node-gyp configure --msvs_version=2019"
"npm config set python /path/to/executable/python"

On Environment Variables, i set on System Variables, the path with "C:\Python39\Scripts\" and "C:\Python39\". 

I followed again this  node-gyp config tutorial, on https://github.com/nodejs/node-gyp

I think its it, 
Node -v = 14.16.1
Visual Community 2019
Npm -v = 6.14.12
Again, sorry for take to loog to respond
