### ISSUE TITLE
Rebuild error.

### ISSUE THREAD

**Issue by sddwt** [node-ffi-napi/node-ffi-napi#128]
```
/ Building module: ffi-napi, Completed: 0d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(1784): error C2061: 语法错误: 标识符“napi_callback_scope” [D:\o
thers\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(1792): error C2833: “operator napi_callback_scope”不是 可识别的
运算符或类型 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(1792): error C2059: 语法错误:“newline” [D:\others\igamep\my-
project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(1792): error C2238: 意外的标记位于“;”之前 [D:\others\igamep\my-pr
oject\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(1798): error C3646: “_scope”: 未知重写说明符 [D:\others\igamep\
my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(1798): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
[D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(2017): error C2061: 语法错误: 标识符“napi_threadsafe_function”
[D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(2017): error C2535: “Napi::ThreadSafeFunction::ThreadSaf
eFunction(void)”: 已经定义或声明成员函数 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
  d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(2016): note: 参见“Napi::ThreadSafeFunction::ThreadSafeFu
  nction”的声明
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(2019): error C2833: “operator napi_threadsafe_function”不
是可识别的运算符或类型 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(2019): error C2059: 语法错误:“newline” [D:\others\igamep\my-
project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(2019): error C2238: 意外的标记位于“;”之前 [D:\others\igamep\my-pr
oject\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(2085): error C2061: 语法错误: 标识符“napi_threadsafe_function_c
all_mode” [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(2092): error C3646: “_tsfn”: 未知重写说明符 [D:\others\igamep\m
y-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi.h(2092): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
[D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
- Building module: ffi-napi, Completed: 0d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(213): error C2143: 语法错误: 缺少“;”(在“*”的前面) [D:\others\i
gamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
  d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(214): note: 参见对正在编译的 类 模板 实例化 "Napi::details::Thre
  adSafeFinalize<ContextType,Finalizer,FinalizerDataType>" 的引用
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(213): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 i
nt [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(213): error C2238: 意外的标记位于“;”之前 [D:\others\igamep\my
-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(405): error C2065: “napi_bigint”: 未声明的标识符 [D:\others
\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(416): error C3861: “napi_is_date”: 找不到标识符 [D:\others
\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(648): error C3861: “napi_create_bigint_int64”: 找不到标识
符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(655): error C3861: “napi_create_bigint_uint64”: 找 不到标
识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(662): error C3861: “napi_create_bigint_words”: 找不到标识
符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(675): error C3861: “napi_get_value_bigint_int64”:  找不
到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(683): error C3861: “napi_get_value_bigint_uint64”: 找
不到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(691): error C3861: “napi_get_value_bigint_words”:  找不
到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(698): error C3861: “napi_get_value_bigint_words”:  找不
到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(711): error C3861: “napi_create_date”: 找不到标识符 [D:\ot
hers\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(728): error C3861: “napi_get_date_value”: 找不到标 识符 [D:
\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(3620): error C2061: 语法错误: 标识符“napi_callback_scope” [
D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(3620): error C2065: “scope”: 未声明的标识符 [D:\others\igam
ep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(3620): error C2614: “Napi::CallbackScope”: 非法的成员初始化:
“_scope”不是基或成员 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(3626): error C2065: “_scope”: 未声明的标识符 [D:\others\iga
mep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(3625): error C3861: “napi_open_callback_scope”: 找 不到标
识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(3631): error C2065: “_scope”: 未声明的标识符 [D:\others\iga
mep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(3631): error C3861: “napi_close_callback_scope”: 找不到
标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(3637): error C2833: “operator napi_callback_scope” 不是
可识别的运算符或类型 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(3637): error C2589: “operator”:“::”右边的非法标记 [D:\other
s\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(3637): error C2062: 意外的类型“unknown-type” [D:\others\i
gamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(3637): error C2143: 语法错误: 缺少“;”(在“{”的前面) [D:\others\
igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(3637): error C2447: “{”: 缺少函数标题(是否是老式的 形式表?) [D:\othe
rs\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4075): error C2614: “Napi::ThreadSafeFunction”: 非 法的成
员初始化:“_tsfn”不是基或成员 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4079): error C2065: “napi_threadsafe_function”: 未 声明的
标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4079): error C2146: 语法错误: 缺少“)”(在标识符“tsfn”的前面) [D:\o
thers\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4080): error C2065: “tsfn”: 未声明的标识符 [D:\others\igame
p\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4080): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认
int [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4080): error C2448: “Napi::_tsfn”: 函数样式初始值设定项类似函数定义
[D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4083): error C2833: “operator napi_threadsafe_functi
on”不是可识别的运算符或类型 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4083): error C2589: “operator”:“::”右边的非法标记 [D:\other
s\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4083): error C2062: 意外的类型“unknown-type” [D:\others\i
gamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4083): error C2143: 语法错误: 缺少“;”(在“{”的前面) [D:\others\
igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4083): error C2447: “{”: 缺少函数标题(是否是老式的 形式表?) [D:\othe
rs\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4088): error C2065: “napi_tsfn_blocking”: 未声明的 标识符 [D
:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4094): error C2065: “napi_tsfn_blocking”: 未声明的 标识符 [D
:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4094): error C3861: “napi_call_threadsafe_function”:
 找不到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4113): error C2065: “napi_tsfn_nonblocking”: 未声明的标识符
 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4119): error C2065: “napi_tsfn_nonblocking”: 未声明的标识符
 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4119): error C3861: “napi_call_threadsafe_function”:
 找不到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4138): error C2446: “!=”: 没有从“nullptr”到“int ”的转换 [D:\
others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
  d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4138): note: 本机 nullptr 只能转换为 bool 或使用 reinterpret
  _cast 转换为整型
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4139): error C3861: “napi_ref_threadsafe_function”:
找不到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4145): error C2446: “!=”: 没有从“nullptr”到“int ”的转换 [D:\
others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
  d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4145): note: 本机 nullptr 只能转换为 bool 或使用 reinterpret
  _cast 转换为整型
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4146): error C3861: “napi_unref_threadsafe_function ”
: 找不到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4152): error C3861: “napi_acquire_threadsafe_functio
n”: 找不到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4156): error C2065: “napi_tsfn_release”: 未声明的标识符 [D:
\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4156): error C3861: “napi_release_threadsafe_functio
n”: 找不到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4160): error C2065: “napi_tsfn_abort”: 未声明的标识符 [D:\o
thers\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
\ Building module: ffi-napi, Completed: 0d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4160): error C3861: “napi_release_threadsafe_functio
n”: 找不到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4166): error C3861: “napi_get_threadsafe_function_co
ntext”: 找不到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4204): error C2061: 语法错误: 标识符“napi_threadsafe_functi
on_call_mode” [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4206): error C2065: “mode”: 未声明的标识符 [D:\others\igame
p\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\node-addon-api\napi-inl.h(4205): error C3861: “napi_call_threadsafe_function”:
 找不到标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\get-uv-event-loop-napi-h\include\get-uv-event-loop-napi.h(26): error C2065: “n
api_get_uv_event_loop”: 未声明的标识符 [D:\others\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\ffi-napi\src\ffi.cc(11): error C3861: “napi_get_instance_data”: 找不到标识符 [D:\oth
ers\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
d:\others\igamep\my-project\node_modules\ffi-napi\src\ffi.cc(347): error C3861: “napi_set_instance_data”: 找不到标识符 [D:\ot
hers\igamep\my-project\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'D:\others\igamep\my-project\node_modules\ffi-napi'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1



Error: node-gyp failed to rebuild 'D:\others\igamep\my-project\node_modules\ffi-napi'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1


    at ModuleRebuilder.rebuildNodeGypModule (D:\others\igamep\my-project\node_modules\electron-rebuild\lib\src\module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (D:\others\igamep\my-project\node_modules\electron-rebuild\lib\src\rebuild.js:190:9)
    at async Rebuilder.rebuild (D:\others\igamep\my-project\node_modules\electron-rebuild\lib\src\rebuild.js:152:17)
    at async D:\others\igamep\my-project\node_modules\electron-rebuild\lib\src\cli.js:146:9

D:\others\igamep\my-project>npm install
npm WARN bootstrap@4.0.0-beta.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN jiasuqi@0.0.1 No repository field.
npm WARN jiasuqi@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
```

Node verision is: v14.15.4
npm version is: 6.14.11
ffi-napi: ^3.1.0,
ref-napi: ^3.0.1

I'll be very appreciate if you cound help me. Thanks.

**Comment by Beshelmek** [comment]
Same error.

**Comment by 189** [comment]
Node v12 is works good, but node v14 failed same as you. So I just reduce the version number to 12.22.1 and fixed it
