### ISSUE TITLE
Prebuilds?

### ISSUE THREAD

**Issue by Kreijstal** [node-ffi-napi/node-ffi-napi#149]
Can I use this without needing a developer enviroment? I can't install a compiler. (Because I don't have permissions)

**Comment by vweevers** [comment]
Yes, prebuilds are included in the npm package, for linux, windows, osx and arm64, since https://github.com/node-ffi-napi/node-ffi-napi/pull/63.

**Comment by Kreijstal** [comment]
ohh, ok.. for a totally newbie question unrelated to this project, (maybe useful to someone else), how do I do `npm install` without defaulting to node-gyp? but to just use the prebuilds?

**Comment by addaleax** [comment]
The default is to use prebuilds, but you can use `npm install --build-from-source` to disable that. It will also build from source if no prebuilt versions are available for your system.

**Comment by Kreijstal** [comment]
so if it errors because of node-gyp that tries to compiler, that means that there are no builds for my system? that's strange, since it's just windows 10 x64

**Comment by addaleax** [comment]
@Kreijstal If you want to know answers to that, we’ll need to know what exactly you are installing (which version) and the full output you get from npm (and/or the debug log that its error message refers to)

**Comment by Kreijstal** [comment]
```>npm install ffi-napi
npm ERR! code 1
npm ERR! path C:\somepath\ok\scripts\node_modules\ffi-napi
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.6.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.1 found at "C:\somepath\scoop\apps\python\current\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:340:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1065:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "C:\\somepath\\scoop\\apps\\nodejs\\current\\node.exe" "C:\\somepath\\scoop\\persist\\nodejs\\bin\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\somepath\ok\scripts\node_modules\ffi-napi
npm ERR! gyp ERR! node -v v15.6.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\somepath\scoop\persist\nodejs\cache\_logs\2021-04-16T08_20_55_004Z-debug.lognpm ERR! code 1
npm ERR! path C:\somepath\ok\scripts\node_modules\ffi-napi
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.6.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.1 found at "C:\somepath\scoop\apps\python\current\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:340:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1065:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "C:\\somepath\\scoop\\apps\\nodejs\\current\\node.exe" "C:\\somepath\\scoop\\persist\\nodejs\\bin\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\somepath\ok\scripts\node_modules\ffi-napi
npm ERR! gyp ERR! node -v v15.6.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\somepath\scoop\persist\nodejs\cache\_logs\2021-04-16T08_20_55_004Z-debug.log
```

ok lets see the log
C:\somepath\scoop\persist\nodejs\cache\_logs\2021-04-16T08_20_55_004Z-debug.log
```
0 verbose cli [
0 verbose cli   'C:\\somepath\\scoop\\apps\\nodejs\\current\\node.exe',
0 verbose cli   'C:\\somepath\\scoop\\apps\\nodejs\\current\\bin\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   'ffi-napi'
0 verbose cli ]
1 info using npm@7.9.0
2 info using node@v15.6.0
3 timing npm:load:whichnode Completed in 4ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\npmrc Completed in 7ms
6 timing config:load:builtin Completed in 7ms
7 timing config:load:cli Completed in 7ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\somepath\ok\scripts\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\somepath\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\somepath\scoop\persist\nodejs\bin\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 22ms
18 timing npm:load:configload Completed in 22ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 2ms
21 timing npm:load:cleanupLog Completed in 3ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 1ms
24 timing npm:load Completed in 33ms
25 timing config:load:flatten Completed in 4ms
26 timing arborist:ctor Completed in 1ms
27 timing idealTree:init Completed in 44ms
28 timing idealTree:userRequests Completed in 1ms
29 silly idealTree buildDeps
30 silly fetch manifest ffi-napi@*
31 timing arborist:ctor Completed in 0ms
32 http fetch GET 304 https://registry.npmjs.org/ffi-napi 553ms (from cache)
33 silly placeDep ROOT ffi-napi@4.0.3 OK for: scripts@1.0.0 want: *
34 silly fetch manifest debug@^4.1.1
35 silly fetch manifest get-uv-event-loop-napi-h@^1.0.5
36 silly fetch manifest node-addon-api@^3.0.0
37 silly fetch manifest node-gyp-build@^4.2.1
38 silly fetch manifest ref-napi@^2.0.1 || ^3.0.2
39 silly fetch manifest ref-struct-di@^1.1.0
40 http fetch GET 304 https://registry.npmjs.org/get-uv-event-loop-napi-h 113ms (from cache)
41 http fetch GET 304 https://registry.npmjs.org/node-gyp-build 113ms (from cache)
42 http fetch GET 304 https://registry.npmjs.org/debug 121ms (from cache)
43 http fetch GET 304 https://registry.npmjs.org/ref-napi 118ms (from cache)
44 http fetch GET 304 https://registry.npmjs.org/node-addon-api 234ms (from cache)
45 http fetch GET 304 https://registry.npmjs.org/ref-struct-di 873ms (from cache)
46 timing idealTree:#root Completed in 1442ms
47 silly placeDep ROOT debug@4.3.1 OK for: ffi-napi@4.0.3 want: ^4.1.1
48 silly placeDep ROOT get-uv-event-loop-napi-h@1.0.6 OK for: ffi-napi@4.0.3 want: ^1.0.5
49 silly placeDep ROOT node-addon-api@3.1.0 OK for: ffi-napi@4.0.3 want: ^3.0.0
50 silly placeDep ROOT node-gyp-build@4.2.3 OK for: ffi-napi@4.0.3 want: ^4.2.1
51 silly placeDep ROOT ref-napi@3.0.2 OK for: ffi-napi@4.0.3 want: ^2.0.1 || ^3.0.2
52 silly placeDep ROOT ref-struct-di@1.1.1 OK for: ffi-napi@4.0.3 want: ^1.1.0
53 silly fetch manifest ms@2.1.2
54 silly fetch manifest get-symbol-from-current-process-h@^1.0.1
55 silly fetch manifest get-symbol-from-current-process-h@^1.0.2
56 silly fetch manifest node-addon-api@^2.0.0
57 silly fetch manifest debug@^3.1.0
58 http fetch GET 304 https://registry.npmjs.org/get-symbol-from-current-process-h 88ms (from cache)
59 http fetch GET 304 https://registry.npmjs.org/ms 95ms (from cache)
60 timing idealTree:node_modules/ffi-napi Completed in 122ms
61 silly placeDep ROOT ms@2.1.2 OK for: debug@4.3.1 want: 2.1.2
62 timing idealTree:node_modules/debug Completed in 2ms
63 silly placeDep ROOT get-symbol-from-current-process-h@1.0.2 OK for: get-uv-event-loop-napi-h@1.0.6 want: ^1.0.1
64 timing idealTree:node_modules/get-uv-event-loop-napi-h Completed in 1ms
65 timing idealTree:node_modules/get-symbol-from-current-process-h Completed in 0ms
66 timing idealTree:node_modules/ms Completed in 1ms
67 timing idealTree:node_modules/node-addon-api Completed in 0ms
68 timing idealTree:node_modules/node-gyp-build Completed in 0ms
69 silly placeDep node_modules/ref-napi node-addon-api@2.0.2 OK for: ref-napi@3.0.2 want: ^2.0.0
70 timing idealTree:node_modules/ref-napi Completed in 1ms
71 silly placeDep node_modules/ref-struct-di debug@3.2.7 OK for: ref-struct-di@1.1.1 want: ^3.1.0
72 timing idealTree:node_modules/ref-struct-di Completed in 2ms
73 timing idealTree:node_modules/ref-napi/node_modules/node-addon-api Completed in 0ms
74 timing idealTree:node_modules/ref-struct-di/node_modules/debug Completed in 0ms
75 timing idealTree:buildDeps Completed in 1574ms
76 timing idealTree:fixDepFlags Completed in 0ms
77 timing idealTree Completed in 1623ms
78 timing reify:loadTrees Completed in 1624ms
79 timing reify:diffTrees Completed in 2ms
80 silly reify moves {}
81 timing reify:retireShallow Completed in 0ms
82 timing reify:createSparse Completed in 7ms
83 timing reify:loadBundles Completed in 0ms
84 timing reifyNode:node_modules/ms Completed in 236ms
85 timing reifyNode:node_modules/node-gyp-build Completed in 254ms
86 timing reifyNode:node_modules/get-symbol-from-current-process-h Completed in 258ms
87 timing reifyNode:node_modules/get-uv-event-loop-napi-h Completed in 259ms
88 timing reifyNode:node_modules/debug Completed in 261ms
89 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 271ms
90 timing auditReport:getReport Completed in 273ms
91 timing auditReport:init Completed in 1ms
92 timing reify:audit Completed in 274ms
93 timing reifyNode:node_modules/ref-struct-di/node_modules/debug Completed in 270ms
94 timing reifyNode:node_modules/ref-struct-di Completed in 276ms
95 timing reifyNode:node_modules/ref-napi/node_modules/node-addon-api Completed in 498ms
96 timing reifyNode:node_modules/node-addon-api Completed in 508ms
97 timing reifyNode:node_modules/ref-napi Completed in 606ms
98 timing reifyNode:node_modules/ffi-napi Completed in 1837ms
99 timing reify:unpack Completed in 1840ms
100 timing reify:unretire Completed in 0ms
101 timing build:queue Completed in 2ms
102 timing build:link:node_modules/node-gyp-build Completed in 17ms
103 timing build:link Completed in 17ms
104 info run ffi-napi@4.0.3 install node_modules/ffi-napi node-gyp-build
105 info run ref-napi@3.0.2 install node_modules/ref-napi node-gyp-build
106 info run ref-napi@3.0.2 install { code: 0, signal: null }
107 timing build:run:install:node_modules/ref-napi Completed in 814ms
108 info run ffi-napi@4.0.3 install { code: 1, signal: null }
109 timing reify:rollback:createSparse Completed in 262ms
110 timing reify:rollback:retireShallow Completed in 0ms
111 timing command:install Completed in 10018ms
112 verbose stack Error: command failed
112 verbose stack     at ChildProcess.<anonymous> (C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
112 verbose stack     at ChildProcess.emit (node:events:379:20)
112 verbose stack     at maybeClose (node:internal/child_process:1065:16)
112 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:296:5)
113 verbose pkgid ffi-napi@4.0.3
114 verbose cwd C:\somepath\ok\scripts
115 verbose Windows_NT 10.0.19041
116 verbose argv "C:\\somepath\\scoop\\apps\\nodejs\\current\\node.exe" "C:\\somepath\\scoop\\apps\\nodejs\\current\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "ffi-napi"
117 verbose node v15.6.0
118 verbose npm  v7.9.0
119 error code 1
120 error path C:\somepath\ok\scripts\node_modules\ffi-napi
121 error command failed
122 error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
123 error gyp info it worked if it ends with ok
123 error gyp info using node-gyp@7.1.2
123 error gyp info using node@15.6.0 | win32 | x64
123 error gyp info find Python using Python version 3.9.1 found at "C:\somepath\scoop\apps\python\current\python.exe"
123 error gyp ERR! find VS
123 error gyp ERR! find VS msvs_version not set from command line or npm config
123 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
123 error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
123 error gyp ERR! find VS looking for Visual Studio 2015
123 error gyp ERR! find VS - not found
123 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
123 error gyp ERR! find VS
123 error gyp ERR! find VS **************************************************************
123 error gyp ERR! find VS You need to install the latest version of Visual Studio
123 error gyp ERR! find VS including the "Desktop development with C++" workload.
123 error gyp ERR! find VS For more information consult the documentation at:
123 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
123 error gyp ERR! find VS **************************************************************
123 error gyp ERR! find VS
123 error gyp ERR! configure error
123 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
123 error gyp ERR! stack     at VisualStudioFinder.fail (C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
123 error gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
123 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
123 error gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
123 error gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
123 error gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
123 error gyp ERR! stack     at C:\somepath\scoop\persist\nodejs\bin\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
123 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:340:5)
123 error gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
123 error gyp ERR! stack     at maybeClose (node:internal/child_process:1065:16)
123 error gyp ERR! System Windows_NT 10.0.19041
123 error gyp ERR! command "C:\\somepath\\scoop\\apps\\nodejs\\current\\node.exe" "C:\\somepath\\scoop\\persist\\nodejs\\bin\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
123 error gyp ERR! cwd C:\somepath\ok\scripts\node_modules\ffi-napi
123 error gyp ERR! node -v v15.6.0
123 error gyp ERR! node-gyp -v v7.1.2
123 error gyp ERR! not ok
124 verbose exit 1
```

**Comment by slgluo** [comment]
the same problem, so how do i solve it?

**Comment by Kreijstal** [comment]
> the same problem, so how do i solve it?

I think it's unsolvable. for now, maybe we will have to recompile node or something

**Comment by xingrz** [comment]
Probably due to #197 and get fixed in #198

**Comment by Kreijstal** [comment]
cant I manually install prebuilds?
