### ISSUE TITLE
Error when trying to install node-ffi-napi

### ISSUE THREAD

**Issue by RiQuY** [node-ffi-napi/node-ffi-napi#15]
To make things clear, I have windows-build-tools installed and I set the npm config to python 2.7 folder. (64 bits node and python).
```
C:\Users\Practicas02\Documents\Proyectos\Navegador Electron ADIF\Aplicacion Electron\electron_adif\app>npm install ffi-napi

> ref-napi@1.4.0 install C:\Users\Practicas02\Documents\Proyectos\Navegador Electron ADIF\Aplicacion Electron\electron_adif\app\node_modules\ref-napi
> node-gyp rebuild


C:\Users\Practicas02\Documents\Proyectos\Navegador Electron ADIF\Aplicacion Electron\electron_adif\app\node_modules\ref-napi>if not defined npm_config_node_gyp (node "C:\Users\Practicas02\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Practicas02\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
  win_delay_load_hook.cc
  Generando c¾digo
  All 1 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Generaci¾n de c¾digo finalizada
  nothing.vcxproj -> C:\Users\Practicas02\Documents\Proyectos\Navegador Electron ADIF\Aplicacion Electron\electron_adif\app\node_modules\ref-napi\build\Release\\nothing.node
  binding.cc
  win_delay_load_hook.cc
     Creando biblioteca C:\Users\Practicas02\Documents\Proyectos\Navegador Electron ADIF\Aplicacion Electron\electron_adif\app\node_modules\ref-napi\build\Release\binding.lib y objeto C:\Users\Practicas02\Documents\Proyectos\Navegad
  or Electron ADIF\Aplicacion Electron\electron_adif\app\node_modules\ref-napi\build\Release\binding.exp
  Generando c¾digo
  All 242 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Generaci¾n de c¾digo finalizada
  binding.vcxproj -> C:\Users\Practicas02\Documents\Proyectos\Navegador Electron ADIF\Aplicacion Electron\electron_adif\app\node_modules\ref-napi\build\Release\\binding.node

> ffi-napi@2.4.3 install C:\Users\Practicas02\Documents\Proyectos\Navegador Electron ADIF\Aplicacion Electron\electron_adif\app\node_modules\ffi-napi
> node-gyp rebuild


C:\Users\Practicas02\Documents\Proyectos\Navegador Electron ADIF\Aplicacion Electron\electron_adif\app\node_modules\ffi-napi>if not defined npm_config_node_gyp (node "C:\Users\Practicas02\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Practicas02\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> C:\Users\Practicas02\Documents\Proyectos\Navegador Electron ADIF\Aplicacion Electron\electron_adif\app\node_modules\ffi-napi\build\Release\\libffi.lib
  nothing.vcxproj -> C:\Users\Practicas02\Documents\Proyectos\Navegador Electron ADIF\Aplicacion Electron\electron_adif\app\node_modules\ffi-napi\build\Release\\nothing.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
c:\users\practicas02\documents\proyectos\navegador electron adif\aplicacion electron\electron_adif\app\node_modules\ffi-napi\src\ffi.cc(3): fatal error C1083: No se puede abrir el archivo incluir: 'get-uv-event-loop-napi.h': No such
 file or directory [C:\Users\Practicas02\Documents\Proyectos\Navegador Electron ADIF\Aplicacion Electron\electron_adif\app\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Practicas02\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Practicas02\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Practicas02\Documents\Proyectos\Navegador Electron ADIF\Aplicacion Electron\electron_adif\app\node_modules\ffi-napi
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint@^4.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@1.9.0 requires a peer of eslint@>=1.6.0 <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@2.4.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi-napi@2.4.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Practicas02\AppData\Roaming\npm-cache\_logs\2018-10-08T08_18_49_857Z-debug.log
```

**Comment by JVisona** [comment]
Got the same problem, ive installed it on a project, worked correctly, after trying to install on another project it just dont work anymrore

**Comment by CountDucoo** [comment]
Same error here.  

fatal error C1083: Cannot open include file: 'get-uv-event-loop-napi.h': No such file or directory [C:\Code Base\electron-client\node_modules\ffi-napi\build\ffi_bindings.vcxproj]

get-uv-event-loop-napi-h is installed.

**Comment by CountDucoo** [comment]
solved by manually copy the h.file you need to C:\Users\<yoursuer>\.node-gyp\<version>\include\node

**Comment by mortezaataiy** [comment]
> solved by manually copy the h.file you need to C:\Users<yoursuer>.node-gyp<version>\include\node

Where can I find the file? I search the file's name in all drives but I didn't find :(

**Comment by CountDucoo** [comment]
run npm install 
it will throw error that get-uv-event-loop-napi.h file can not be found
download get-uv-event-loop-napi, copy the .h file into <your project>\node_modules\node-addon-api\
run install again, it will work
do the same for other  .h files.

Hope that works for you

**Comment by RiQuY** [comment]
The original repo at https://github.com/node-ffi/node-ffi worked again, just use that instead of ffi-napi.

**Comment by DanielAskTia** [comment]
The issue is most likely spaces in the directory name.  Install node-ffi-napi to a directory w/o spaces and it should succeed.

**Comment by AjManoj** [comment]
@DanielAskTia  Worked for me

**Comment by thePaulKelley** [comment]
This happens when you try to install node-gyp packages with python 3 as the default python. The node-gyp package requires python 2.7.xx. Even if you set python 2.7 as the default in npm config, node-gyp may run the default python triggering this error. 

However you can resolve the issue by running the install in a python 2.7 virtual environment. Use [virtualenv](https://docs.python-guide.org/dev/virtualenvs/), [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html), or similar to create the environment. Switch to that environment. The install should now work. 

Using virtualenv

```
# Example of using virtualenv to install a virtual environment on OSX
# Run this in your working directory, add to .gitignore
# Note, if you installed python via Anaconda this will not work, use below

$ pip install virtualenv
$ virtualenv --python=/usr/bin/python2.7 myenv
$ source myenv/bin/activate

# now run the program you were using to do the installs
(myenv) $ yarn install
```
Using Anaconda's conda

```
# Use this if Anaconda is installed
# Example of using conda to make and use a virtual environment 

$ conda create --name myenv python=2.7.8
$ conda activate myenv

# now run the program you were using to do the installs
(myenv) $ yarn install   
```
Note you only need the virtual environment for the install. Once installed you should be able to run yarn dev, or similar, in the default environment.

**Comment by maaelphd** [comment]
> The issue is most likely spaces in the directory name. Install node-ffi-napi to a directory w/o spaces and it should succeed.

Thanks. This worked for me, but in my case, it was a - "hyphen". My folder name was like "namex-namey", i change to namex_namey, and worked fine.
