### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by leehambley** [node-ffi-napi/node-ffi-napi#152]
We are in a testing scenario with `jest` and experiencing the following error when we introduced a 2nd test file.. Both test files start with the given preamble/require lines.

The important thing is that `test/node/parse-config-test.js` works flawlessly, and also has the same preamble, but whatever file runs 2nd runs into this error.

```
 FAIL  test/node/diff-test.js
  ● Test suite failed to run

    RangeError: Maximum call stack size exceeded

      at debug (node_modules/debug/src/common.js:1:1)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:742:3)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
```

```
const libourthing = require("../../src/ffi/node");
```

```
// src/ffi/node/index.js
var ffi = require("ffi-napi");
var ref = require("ref-napi");
var Struct = require("ref-struct-di")(ref);
var Array = require("ref-array-di")(ref);

/// lots of types and callbacks
let libourthing = ffi.Library("./target/debug/libourthing", {
  init_logger: ["void", [LogCallbacksPtr]],
  config_from_file: [ConfigurationPtr, [ref.types.CString]],
});

// exports
module.exports = mitre;
module.exports.default = mitre;
```

We have run the same suite with `DEBUG=ffi:*,ref npx jest > firehose.txt > 2>&1` and that `firehose.txt` file is attached. 

We did some preliminary investigation, but it seems like at around line `450` of the `firehose.txt` that we run into this thing:

```
2021-04-16T19:56:00.287Z ref creating a reference to buffer <Buffer@0x(nil) type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set], name: 'void' }>
2021-04-16T19:56:00.287Z ref allocating Buffer for type with "size" 0
2021-04-16T19:56:00.287Z ref setting value on allocated buffer <Buffer@0x(nil) type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set], name: 'void' }>
2021-04-16T19:56:00.287Z ref set(): (offset: 0) <Buffer@0x49082a0 00 00 00 00 00 00 00 00, type: { indirection: 2, name: 'void*' }> <Buffer@0x(nil) type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set], name: 'void' }>
2021-04-16T19:56:00.287Z ref writing pointer to buffer <Buffer@0x49082a0 00 00 00 00 00 00 00 00, type: { indirection: 2, name: 'void*' }> 0 <Buffer@0x(nil) type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set], name: 'void' }>
2021-04-16T19:56:00.287Z ref writing pointer to buffer <Buffer@0x49082a0 00 00 00 00 00 00 00 00, type: { indirection: 2, name: 'void*' }> 0 <Buffer@0x(nil) type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set], name: 'void' }>
2021-04-16T19:56:00.287Z ref writing pointer to buffer <Buffer@0x49082a0 00 00 00 00 00 00 00 00, type: { indirection: 2, name: 'void*' }> 0 <Buffer@0x(nil) type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set], name: 'void' }>
2021-04-16T19:56:00.288Z ref writing pointer to buffer <Buffer@0x49082a0 00 00 00 00 00 00 00 00, type: { indirection: 2, name: 'void*' }> 0 <Buffer@0x(nil) type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set], name: 'void' }>
2021-04-16T19:56:00.288Z ref writing pointer to buffer <Buffer@0x49082a0 00 00 00 00 00 00 00 00, type: { indirection: 2, name: 'void*' }> 0 <Buffer@0x(nil) type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set], name: 'void' }>
2021-04-16T19:56:00.288Z ref writing pointer to buffer <Buffer@0x49082a0 00 00 00 00 00 00 00 00, type: { indirection: 2, name: 'void*' }> 0 <Buffer@0x(nil) type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set], name: 'void' }>
2021-04-16T19:56:00.288Z ref writing pointer to buffer <Buffer@0x49082a0 00 00 00 00 00 00 00 00, type: { indirection: 2, name: 'void*' }> 0 <Buffer@0x(nil) type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set], name: 'void' }>
2021-04-16T19:56:00.288Z ref writing pointer to buffer <Buffer@0x49082a0 00 00 00 00 00 00 00 00, type: { indirection: 2, name: 'void*' }> 0 <Buffer@0x(nil) type: { size: 0, indirection: 1, get: [Function: get], set: [Function: set], name: 'void' }>
```

The place in the `firehose.txt` is right after the first test file ran to completion, and we're running the 2nd one, and it seems relevant. 

A couple of other observations:

- Changing `jest` run options (e.g `--runInBand`, and setting the worker concurrency) didn't make a difference.
- A simple `require('ffi-napi'); require('ffi-napi')` twice doesn't seem to reproduce it.
- We're opening the issue in `ffi-napi` because although `ref-napi` is heavily implicated in all the `debug` package logs the initial library calling into `ref-napi` is `ffi-napi` here, visible if we set `Error.stackTraceLimit = Infinity`:

```
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer [as _writePointer] (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.writePointer (node_modules/ref-napi/lib/ref.js:743:11)
      at Object.set (node_modules/ref-napi/lib/ref.js:494:13)
      at Object.alloc (node_modules/ref-napi/lib/ref.js:526:13)
      at Object.ref (node_modules/ref-napi/lib/ref.js:638:18)
      at Object.<anonymous> (node_modules/ref-napi/lib/ref.js:1220:32)
      at Object.<anonymous> (node_modules/ffi-napi/lib/ffi.js:7:13)
      at Object.<anonymous> (src/ffi/node/index.js:1:100)
      at Object.<anonymous> (test/node/diff-test.js:3:15)
```

[firehose.txt](https://github.com/node-ffi-napi/node-ffi-napi/files/6327638/firehose.txt)

**Comment by addaleax** [comment]
https://github.com/node-ffi-napi/ref-napi/issues/16 – should be gone with a recent version of ref-napi? That being said, we’re not really in the business of fixing jest’s problems.

**Comment by leehambley** [comment]
Hey @addaleax thanks for the amazing fast response. 

Indeed, we had a stale `package.json` from September 2020. Our *sincere* apologies.

Hopefully this issue serves to direct the next adventurers to the `ref-napi` issue you kindly linked above.

Herzlichen danke von Hamburg aus.
