### ISSUE TITLE
Unable to build on ubuntu

### ISSUE THREAD

**Issue by deinBestFreund** [node-ffi-napi/node-ffi-napi#155]
Hello, I am trying to build a napi app from ubuntu 20.04 but it gives the following error:

npm install

> ffi-napi@4.0.3 install /media/user/334d9ee4-73d7-4ef9-89fc-a6c6294adcdd/mapSelector-main/node_modules/ffi-napi
> node-gyp-build

make: Entering directory '/media/user/334d9ee4-73d7-4ef9-89fc-a6c6294adcdd/mapSelector-main/node_modules/ffi-napi/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
../deps/libffi/src/java_raw_api.c: In function ‘ffi_java_raw_call’:
../deps/libffi/src/java_raw_api.c:317:3: warning: ‘ffi_java_raw_to_ptrarray’ is deprecated [-Wdeprecated-declarations]
  317 |   ffi_java_raw_to_ptrarray (cif, raw, avalue);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
../deps/libffi/src/java_raw_api.c:76:1: note: declared here
   76 | ffi_java_raw_to_ptrarray (ffi_cif *cif, ffi_java_raw *raw, void **args)
      | ^~~~~~~~~~~~~~~~~~~~~~~~
../deps/libffi/src/java_raw_api.c: In function ‘ffi_java_translate_args’:
../deps/libffi/src/java_raw_api.c:328:3: warning: ‘ffi_java_raw_size’ is deprecated [-Wdeprecated-declarations]
  328 |   ffi_java_raw *raw = (ffi_java_raw*)alloca (ffi_java_raw_size (cif));
      |   ^~~~~~~~~~~~
../deps/libffi/src/java_raw_api.c:45:1: note: declared here
   45 | ffi_java_raw_size (ffi_cif *cif)
      | ^~~~~~~~~~~~~~~~~
../deps/libffi/src/java_raw_api.c:331:3: warning: ‘ffi_java_ptrarray_to_raw’ is deprecated [-Wdeprecated-declarations]
  331 |   ffi_java_ptrarray_to_raw (cif, avalue, raw);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
../deps/libffi/src/java_raw_api.c:157:1: note: declared here
  157 | ffi_java_ptrarray_to_raw (ffi_cif *cif, void **args, ffi_java_raw *raw)
      | ^~~~~~~~~~~~~~~~~~~~~~~~
../deps/libffi/src/java_raw_api.c: In function ‘ffi_prep_java_raw_closure’:
../deps/libffi/src/java_raw_api.c:369:3: warning: ‘ffi_prep_java_raw_closure_loc’ is deprecated [-Wdeprecated-declarations]
  369 |   return ffi_prep_java_raw_closure_loc (cl, cif, fun, user_data, cl);
      |   ^~~~~~
../deps/libffi/src/java_raw_api.c:337:1: note: declared here
  337 | ffi_prep_java_raw_closure_loc (ffi_java_raw_closure* cl,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
../deps/libffi/src/closures.c: In function ‘allocate_space’:
../deps/libffi/src/closures.c:748:29: warning: comparison of integer expressions of different signedness: ‘off_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  748 |       off_t to_write = (len < page_size) ? len : page_size;
      |                             ^
../deps/libffi/src/closures.c:748:44: warning: operand of ?: changes signedness from ‘off_t’ {aka ‘long int’} to ‘size_t’ {aka ‘long unsigned int’} due to unsignedness of other operand [-Wsign-compare]
  748 |       off_t to_write = (len < page_size) ? len : page_size;
      |                                            ^~~
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffiw64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:200:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
  200 |    FFI_ASSERT (0);
      |                  ^
../deps/libffi/src/x86/ffi64.c:175:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
  175 |       {
      |       ^
../deps/libffi/src/x86/ffi64.c:202:5: note: here
  202 |     case FFI_TYPE_FLOAT:
      |     ^~~~
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/win64.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
In file included from /media/user/334d9ee4-73d7-4ef9-89fc-a6c6294adcdd/mapSelector-main/node_modules/node-addon-api/napi.h:2636,
                 from ../src/ffi.h:2,
                 from ../src/ffi.cc:3:
/media/user/334d9ee4-73d7-4ef9-89fc-a6c6294adcdd/mapSelector-main/node_modules/node-addon-api/napi-inl.h: In member function ‘T* Napi::Env::GetInstanceData()’:
/media/user/334d9ee4-73d7-4ef9-89fc-a6c6294adcdd/mapSelector-main/node_modules/node-addon-api/napi-inl.h:469:24: error: there are no arguments to ‘napi_get_instance_data’ that depend on a template parameter, so a declaration of ‘napi_get_instance_data’ must be available [-fpermissive]
  469 |   napi_status status = napi_get_instance_data(_env, &data);
      |                        ^~~~~~~~~~~~~~~~~~~~~~
/media/user/334d9ee4-73d7-4ef9-89fc-a6c6294adcdd/mapSelector-main/node_modules/node-addon-api/napi-inl.h:469:24: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../src/ffi.cc: In static member function ‘static FFI::InstanceData* FFI::InstanceData::Get(Napi::Env)’:
../src/ffi.cc:11:24: error: ‘napi_get_instance_data’ was not declared in this scope; did you mean ‘napi_new_instance’?
   11 |   napi_status status = napi_get_instance_data(env, &d);
      |                        ^~~~~~~~~~~~~~~~~~~~~~
      |                        napi_new_instance
../src/ffi.cc: In function ‘Napi::Object BindingHook(Napi::Env, Napi::Object)’:
../src/ffi.cc:348:24: error: ‘napi_set_instance_data’ was not declared in this scope; did you mean ‘napi_new_instance’?
  348 |   napi_status status = napi_set_instance_data(
      |                        ^~~~~~~~~~~~~~~~~~~~~~
      |                        napi_new_instance
make: *** [ffi_bindings.target.mk:116: Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory '/media/user/334d9ee4-73d7-4ef9-89fc-a6c6294adcdd/mapSelector-main/node_modules/ffi-napi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/media/user/334d9ee4-73d7-4ef9-89fc-a6c6294adcdd/mapSelector-main/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.8.0-50-generic
gyp ERR! command "/usr/bin/node" "/media/user/334d9ee4-73d7-4ef9-89fc-a6c6294adcdd/mapSelector-main/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/user/334d9ee4-73d7-4ef9-89fc-a6c6294adcdd/mapSelector-main/node_modules/ffi-napi
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v8.0.0
gyp ERR! not ok 
npm WARN mapselector@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@4.0.3 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi-napi@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-05-04T21_17_28_115Z-debug.log

Any help appreciated!

**Comment by deinBestFreund** [comment]
upgrading electron or downgrading the lib should solve the problem
