### ISSUE TITLE
Error: Dynamic Linking Error: dlopen(./libtcpserver.so.dylib, 2): image not found

### ISSUE THREAD

**Issue by pplmx** [node-ffi-napi/node-ffi-napi#174]
```text
❯ node tcp_server.js
/Users/mystic/test/node_modules/ffi-napi/lib/dynamic_library.js:75
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: dlopen(./libtcpserver.so.dylib, 2): image not found
    at new DynamicLibrary (/Users/mystic/test/node_modules/ffi-napi/lib/dynamic_library.js:75:11)
    at Object.Library (/Users/mystic/test/node_modules/ffi-napi/lib/library.js:47:10)
    at Object.<anonymous> (/Users/mystic/test/encryption/tcp_server.js:21:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by pplmx** [comment]
Could anyone give me some help? Thanks a lot. :)

**Comment by pplmx** [comment]
Fixed.

```shell
go build -o libtcpserver.so -buildmode=c-shared server.go

# if macOS, you also need run the following
go build -o libtcpserver.so.dylib -buildmode=c-shared server.go
```
