### ISSUE TITLE
***tmp.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by Omiga3721** [node-ffi-napi/node-ffi-napi#181]
node-ffi-napi is used in my electron project.   Just require did nothing. but  no problem under mac

<img width="1506" alt="ffi-napi" src="https://user-images.githubusercontent.com/24944112/138164123-f972fd01-13c6-45ae-a131-ef659326610b.png">

```
vue-router.esm-bundler.js?6c02:3295 Error: \\?\C:\Users\M2Macbook\AppData\Local\Temp\2d205273-cbda-4db9-81aa-d4d042f1f3bf.tmp.node is not a valid Win32 application.
\\?\C:\Users\M2Macbook\AppData\Local\Temp\2d205273-cbda-4db9-81aa-d4d042f1f3bf.tmp.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at load (C:\Users\M2Macbook\Desktop\electron-test\resources\app.asar\node_modules\node-gyp-build\index.js:21:10)
triggerError @ vue-router.esm-bundler.js?6c02:3295
electron/js2c/asar_bundle.js:5 Uncaught (in promise) Error: \\?\C:\Users\M2Macbook\AppData\Local\Temp\2d205273-cbda-4db9-81aa-d4d042f1f3bf.tmp.node is not a valid Win32 application.
\\?\C:\Users\M2Macbook\AppData\Local\Temp\2d205273-cbda-4db9-81aa-d4d042f1f3bf.tmp.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at load (C:\Users\M2Macbook\Desktop\electron-test\resources\app.asar\node_modules\node-gyp-build\index.js:21:10)

```

vue.config.js
```js
{
  "name": "shoplist",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "dev": "vite",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "core-js": "^3.6.5",
    "electron-store": "^8.0.0",
    "element-plus": "1.1.0-beta.12",
    "ffi-napi": "^4.0.3",
    "jquery": "^3.6.0",
    "ref-array-di": "^1.2.2",
    "ref-napi": "^3.0.3",
    "ref-struct-di": "^1.1.1",
    "vue": "^3.2.2",
    "vue-router": "^4.0.12",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.9.3",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "babel-plugin-component": "^1.1.1",
    "electron": "^13.5.2",
    "electron-builder": "^22.13.1",
    "electron-devtools-installer": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "sass": "^1.43.2",
    "sass-loader": "^7.3.1",
    "vite": "^2.6.4",
    "vue-cli-plugin-electron-builder": "~2.1.1"
  }
}
```

```js
const path = require('path')
const global = require('../../conf/global')
const ffi = require('ffi-napi')  -->  thow error

console.log(path.join(global.global.StaticPath, '/lib/forNodejs'))
// var libfactorial = ffi.Library(path.join(global.global.StaticPath, '/lib/forNodejs'), {
// var libfactorial = ffi.Library(path.join(global.global.StaticPath, '/lib/forNodejs.dll'), {
//     'factorial': ['uint64', ['int']]
// })
// var output = libfactorial.factorial(100)
// console.log('output: ' +  output)
```

**Comment by andyin9** [comment]
@omegamt how did you resolve this problem?

**Comment by anyaoqi** [comment]
我遇到了相同的问题
