### ISSUE TITLE
Dynamic Linking Error: Win32 error 193

### ISSUE THREAD

**Issue by themachho** [node-ffi-napi/node-ffi-napi#184]
Hi, i posted this on [node-ffi](https://github.com/node-ffi/node-ffi/issues/624) without realizing that was outdated. 

Im trying to build a DLL wrapper.  I have a C# project that i want to port with NodeJS (on ElectronJS). On the C# project i dont have issue loading the x64 DLL. 

However when i try to use node-ffi  (ffi-napi) i get error 193. Reading other issues appears to be a x86/x64 issue, but im using node 64 `node -p "process.arch" -> x64`   and `os.arch() -> x64` so i dont understand where is the problem.

My library is `C:\Windows\System32\spool\drivers\x64\3\E_RBL6DAJ` (changed dll name for privacy) and `node --version -> v12.22.7`. 

``` nodejs
var ffi = require('ffi-napi');
var ref = require("ref-napi");
var path = require("path");
var strLibrary = path.join("C:", "Windows", "System32", "spool", "drivers", "x64", "3", "E_RBL6DAJ");
const myDLL = new ffi.Library(strLibrary , {
...
});
```

``` bash
C:\Users\vmuser\Documents\dev\mydll\app_mydll\node_modules\ffi-napi\lib\dynamic_library.js:75
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: Win32 error 193
    at new DynamicLibrary (C:\Users\vmuser\Documents\dev\mydll\app_mydll\node_modules\ffi-napi\lib\dynamic_library.js:75:11)     
    at new Library (C:\Users\vmuser\Documents\dev\mydll\app_mydll\node_modules\ffi-napi\lib\library.js:47:10)
    at Object.<anonymous> (C:\Users\vmuser\Documents\dev\mydll\app_mydll\mydll_wrapper.js:42:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

So the DLL works with C# but no with node-ffi. I have the same arch issue in C# if im calling the x86 version of the DLL. Is there a way that Node is being executed as x86? Im using vscode.
Is there a way to run node as x86 or x64 on the same OS? So i can test both x86 and x64 versions of the DLL.

Thanks!

**Comment by ccreaper** [comment]
I can attest that ffi-napi has an aversion to x64 managed libraries. I can load the x86 library just fine however, but loading in a managed x64 library causes Win32 error 193. I'm using 64-bit nodejs as well.

**Comment by sohaieb** [comment]
Hello guys, any update to this issue please ?

**Comment by zesun96** [comment]
you need a x86 node to install ffi.
download node-x86,and re-run npm install.
