### ISSUE TITLE
electron用ffi-napi

### ISSUE THREAD

**Issue by 2812848295** [node-ffi-napi/node-ffi-napi#204]
今天npm install 突然报错大致意思为
• electron-builder  version=22.14.13
  • rebuilding native dependencies  dependencies=ffi-napi@4.0.3, ref-napi@3.0.3 platform=win32 arch=ia32
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path D:\TerraSync\terrasync\node_modules\ffi-napi
    npm ERR! command failed
    npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@8.4.1
    npm ERR! gyp info using node@16.14.0 | win32 | ia32
    npm ERR! gyp info find Python using Python version 3.10.1 found at "C:\Python310\python.exe"
    npm ERR! gyp info find VS using VS2017 (15.9.28307.1927) found at:
    npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise"
    npm ERR! gyp info find VS run with --verbose for detailed information
    npm ERR! gyp info spawn C:\Python310\python.exe
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   'C:\\node\\node-v16.14.0-win-x86\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'msvs',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'D:\\TerraSync\\terrasync\\node_modules\\ffi-napi\\build\\config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\node\\node-v16.14.0-win-x86\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp\\addon.gypi',      
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\谭运鹏\\.electron-gyp\\11.5.0\\include\\node\\common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\谭运鹏\\.electron-gyp\\11.5.0',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\node\\node-v16.14.0-win-x86\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp',   
    npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\谭运鹏\\\\.electron-gyp\\\\11.5.0\\\\<(target_arch)\\\\node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\TerraSync\\terrasync\\node_modules\\ffi-napi',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'D:\\TerraSync\\terrasync\\node_modules\\ffi-napi\\build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! Traceback (most recent call last):
    npm ERR!   File "C:\node\node-v16.14.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\gyp_main.py", line 45, in <module>
    npm ERR!     sys.exit(gyp.script_main())
    npm ERR!   File "C:\node\node-v16.14.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 662, in script_main
    npm ERR!     return main(sys.argv[1:])
    npm ERR!   File "C:\node\node-v16.14.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 654, in main
    npm ERR!     return gyp_main(args)
    npm ERR!   File "C:\node\node-v16.14.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 639, in gyp_main
    npm ERR!     generator.GenerateOutput(flat_list, targets, data, params)
    npm ERR!   File "C:\node\node-v16.14.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2140, in GenerateOutput
    npm ERR!     _GenerateProject(project, options, msvs_version, generator_flags, spec)
    npm ERR!   File "C:\node\node-v16.14.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1027, in _GenerateProject
    npm ERR!     return _GenerateMSBuildProject(project, options, version, generator_flags, spec)
    npm ERR!   File "C:\node\node-v16.14.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 3823, in _GenerateMSBuildProject
    npm ERR!     easy_xml.WriteXmlIfChanged(content, project.path, pretty=True, win32=True)
    npm ERR!   File "C:\node\node-v16.14.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\easy_xml.py", line 131, in WriteXmlIfChanged
    npm ERR!     existing = file.read()
    npm ERR! UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 2440: illegal multibyte sequence
    npm ERR! gyp ERR! configure error
    npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\node\node-v16.14.0-win-x86\node_modules\npm\node_modules\@npmcli\run-script\node_modules\node-gyp\lib\configure.js:259:16)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    npm ERR! gyp ERR! System Windows_NT 10.0.19042
    npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\node\\node-v16.14.0-win-x86\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"  
    npm ERR! gyp ERR! cwd D:\TerraSync\terrasync\node_modules\ffi-napi
    npm ERR! gyp ERR! node -v v16.14.0
    npm ERR! gyp ERR! node-gyp -v v8.4.1
    npm ERR! gyp ERR! not ok

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\谭运鹏\AppData\Local\npm-cache\_logs\2022-04-22T10_18_07_440Z-debug-0.log

                    command='C:\Program Files\nodejs\node.exe' 'C:\node\node-v16.14.0-win-x86\node_modules\npm\bin\npm-cli.js' rebuild ffi-napi@4.0.3 ref-napi@3.0.3
                    workingDir=
npm ERR! code 1
npm ERR! path D:\TerraSync\terrasync
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c electron-builder install-app-deps

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\谭运鹏\AppData\Local\npm-cache\_logs\2022-04-22T10_18_03_621Z-debug-0.log****

我通过降低python版本或者是其他需要vs的版本 但是还是这样 但是它报错却不影响运行？我还是能正常运行并且调用打包 由于我在网上查阅大量资料一致没有解决 希望可以找到解决办法，这是报错的所有信息 node为16.14.0 python：3.10.1

**Comment by hankjs** [comment]
我的场景使用python2.x，就不会报错
在python3.x我也是这个错误
