### ISSUE TITLE
Dynamic Linking Error: Win32 error 14001

### ISSUE THREAD

**Issue by tengge1** [node-ffi-napi/node-ffi-napi#219]
Code:

```javascript
const path = require('path');
const ffi = require('ffi-napi');

const dll = path.resolve('./dll/elec_test.dll');

const lib = ffi.Library(dll, {
    elec_add: ['int', ['int', 'int']]
});

console.log('1 + 2 = ' + lib.elec_add(1, 2));
```

Error:

```
PS D:\Project\invoke-cpp-test> node .\TestDll.js
D:\Project\invoke-cpp-test\node_modules\ffi-napi\lib\dynamic_library.js:75
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: Win32 error 14001
    at new DynamicLibrary (D:\Project\invoke-cpp-test\node_modules\ffi-napi\lib\dynamic_library.js:75:11)
    at Object.Library (D:\Project\invoke-cpp-test\node_modules\ffi-napi\lib\library.js:47:10)
    at Object.<anonymous> (D:\Project\invoke-cpp-test\TestDll.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by tengge1** [comment]
this may be a problem of the test dll. Sorry to bother.
