### ISSUE TITLE
cannot execute  cause=exit status 1

### ISSUE THREAD

**Issue by ShaopingLin** [node-ffi-napi/node-ffi-napi#223]
```
C:\Users\hasee\Desktop\Background3D\Bg3d>npm run app:dist

> bg3d@0.0.1 app:dist
> electron-builder

  • electron-builder  version=23.3.3 os=10.0.19044
  • description is missed in the package.json  appPackageFile=C:\Users\hasee\Desktop\Background3D\Bg3d\package.json
  • author is missed in the package.json  appPackageFile=C:\Users\hasee\Desktop\Background3D\Bg3d\package.json
  • writing effective config  file=dist\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=ffi-napi@4.0.3, ref-napi@3.0.3, ref-napi@3.0.3 platform=win32 arch=x64
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path C:\Users\hasee\Desktop\Background3D\Bg3d\node_modules\_ffi-napi@4.0.3@ffi-napi
    npm ERR! command failed
    npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\hasee\AppData\Local\Temp\install-c46984a3.cmd
    npm ERR! �ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�-m�����ء�
    npm ERR!   nothing.vcxproj -> C:\Users\hasee\Desktop\Background3D\Bg3d\node_modules\_ffi-napi@4.0.3@ffi-napi\build\Release\\nothing.lib
    npm ERR!   Preprocessing assembly file ..\..\..\deps\libffi\src\x86\win64_intel.preasm
    npm ERR!   ��һ����������ʹ�ô��ļ��������޷����ʡ�
    npm ERR! C:\Users\hasee\Desktop\Background3D\Bg3d\node_modules\_ffi-napi@4.0.3@ffi-napi\build\deps\libffi\ffi.targets(34,5): error MSB3721: ���call call "../../../deps/libffi/preprocess_asm.cmd" "../../../deps/libffi/include" "../../../deps/libffi/config/win/x64" "..\..\..\deps\libffi\src\x86\win64_intel.preasm" "Release\obj\ffi\win64_intel.asm"�����˳������ش���Ϊ 1�� [C:\Users\hasee\Desktop\Background3D\Bg3d\node_modules\_ffi-napi@4.0.3@ffi-napi\build\deps\libffi\ffi.vcxproj]
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.0.0
    npm ERR! gyp info using node@16.17.0 | win32 | x64
    npm ERR! gyp info find Python using Python version 3.10.7 found at "C:\Users\hasee\AppData\Local\Programs\Python\Python310\python.exe"
    npm ERR! gyp info find VS using VS2022 (17.3.32901.215) found at:
    npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
    npm ERR! gyp info find VS run with --verbose for detailed information
    npm ERR! gyp info spawn C:\Users\hasee\AppData\Local\Programs\Python\Python310\python.exe
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   'C:\\Users\\hasee\\AppData\\Roaming\\nvm\\v16.17.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'msvs',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\hasee\\Desktop\\Background3D\\Bg3d\\node_modules\\_ffi-napi@4.0.3@ffi-napi\\build\\config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\hasee\\AppData\\Roaming\\nvm\\v16.17.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\hasee\\.electron-gyp\\20.2.0\\include\\node\\common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\hasee\\.electron-gyp\\20.2.0',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\hasee\\AppData\\Roaming\\nvm\\v16.17.0\\node_modules\\npm\\node_modules\\node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\hasee\\\\.electron-gyp\\\\20.2.0\\\\<(target_arch)\\\\node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\hasee\\Desktop\\Background3D\\Bg3d\\node_modules\\_ffi-napi@4.0.3@ffi-napi',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'C:\\Users\\hasee\\Desktop\\Background3D\\Bg3d\\node_modules\\_ffi-napi@4.0.3@ffi-napi\\build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   'build/binding.sln',
    npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
    npm ERR! gyp info spawn args   '/nologo',
    npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp ERR! build error
    npm ERR! gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\hasee\AppData\Roaming\nvm\v16.17.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    npm ERR! gyp ERR! System Windows_NT 10.0.19044
    npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hasee\\AppData\\Roaming\\nvm\\v16.17.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    npm ERR! gyp ERR! cwd C:\Users\hasee\Desktop\Background3D\Bg3d\node_modules\_ffi-napi@4.0.3@ffi-napi
    npm ERR! gyp ERR! node -v v16.17.0
    npm ERR! gyp ERR! node-gyp -v v9.0.0
    npm ERR! gyp ERR! not ok

    npm ERR! A complete log of this run can be found in:
    npm ERR!     E:\Program Files\nodejs\node_cache\_logs\2022-09-24T12_17_26_056Z-debug-0.log

                    command='C:\Program Files\nodejs\node.exe' 'C:\Users\hasee\AppData\Roaming\nvm\v16.17.0\node_modules\npm\bin\npm-cli.js' rebuild ffi-napi@4.0.3 ref-napi@3.0.3 ref-napi@3.0.3
                    workingDir=
```

**Comment by Chrys4lisfag** [comment]
> ```
> C:\Users\hasee\Desktop\Background3D\Bg3d>npm run app:dist
> 
> > bg3d@0.0.1 app:dist
> > electron-builder
> 
>   • electron-builder  version=23.3.3 os=10.0.19044
>   • description is missed in the package.json  appPackageFile=C:\Users\hasee\Desktop\Background3D\Bg3d\package.json
>   • author is missed in the package.json  appPackageFile=C:\Users\hasee\Desktop\Background3D\Bg3d\package.json
>   • writing effective config  file=dist\builder-effective-config.yaml
>   • rebuilding native dependencies  dependencies=ffi-napi@4.0.3, ref-napi@3.0.3, ref-napi@3.0.3 platform=win32 arch=x64
>   ⨯ cannot execute  cause=exit status 1
>                     errorOut=npm ERR! code 1
>     npm ERR! path C:\Users\hasee\Desktop\Background3D\Bg3d\node_modules\_ffi-napi@4.0.3@ffi-napi
>     npm ERR! command failed
>     npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\hasee\AppData\Local\Temp\install-c46984a3.cmd
>     npm ERR! �ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�-m�����ء�
>     npm ERR!   nothing.vcxproj -> C:\Users\hasee\Desktop\Background3D\Bg3d\node_modules\_ffi-napi@4.0.3@ffi-napi\build\Release\\nothing.lib
>     npm ERR!   Preprocessing assembly file ..\..\..\deps\libffi\src\x86\win64_intel.preasm
>     npm ERR!   ��һ����������ʹ�ô��ļ��������޷����ʡ�
>     npm ERR! C:\Users\hasee\Desktop\Background3D\Bg3d\node_modules\_ffi-napi@4.0.3@ffi-napi\build\deps\libffi\ffi.targets(34,5): error MSB3721: ���call call "../../../deps/libffi/preprocess_asm.cmd" "../../../deps/libffi/include" "../../../deps/libffi/config/win/x64" "..\..\..\deps\libffi\src\x86\win64_intel.preasm" "Release\obj\ffi\win64_intel.asm"�����˳������ش���Ϊ 1�� [C:\Users\hasee\Desktop\Background3D\Bg3d\node_modules\_ffi-napi@4.0.3@ffi-napi\build\deps\libffi\ffi.vcxproj]
>     npm ERR! gyp info it worked if it ends with ok
>     npm ERR! gyp info using node-gyp@9.0.0
>     npm ERR! gyp info using node@16.17.0 | win32 | x64
>     npm ERR! gyp info find Python using Python version 3.10.7 found at "C:\Users\hasee\AppData\Local\Programs\Python\Python310\python.exe"
>     npm ERR! gyp info find VS using VS2022 (17.3.32901.215) found at:
>     npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
>     npm ERR! gyp info find VS run with --verbose for detailed information
>     npm ERR! gyp info spawn C:\Users\hasee\AppData\Local\Programs\Python\Python310\python.exe
>     npm ERR! gyp info spawn args [
>     npm ERR! gyp info spawn args   'C:\\Users\\hasee\\AppData\\Roaming\\nvm\\v16.17.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
>     npm ERR! gyp info spawn args   'binding.gyp',
>     npm ERR! gyp info spawn args   '-f',
>     npm ERR! gyp info spawn args   'msvs',
>     npm ERR! gyp info spawn args   '-I',
>     npm ERR! gyp info spawn args   'C:\\Users\\hasee\\Desktop\\Background3D\\Bg3d\\node_modules\\_ffi-napi@4.0.3@ffi-napi\\build\\config.gypi',
>     npm ERR! gyp info spawn args   '-I',
>     npm ERR! gyp info spawn args   'C:\\Users\\hasee\\AppData\\Roaming\\nvm\\v16.17.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
>     npm ERR! gyp info spawn args   '-I',
>     npm ERR! gyp info spawn args   'C:\\Users\\hasee\\.electron-gyp\\20.2.0\\include\\node\\common.gypi',
>     npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
>     npm ERR! gyp info spawn args   '-Dvisibility=default',
>     npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\hasee\\.electron-gyp\\20.2.0',
>     npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\hasee\\AppData\\Roaming\\nvm\\v16.17.0\\node_modules\\npm\\node_modules\\node-gyp',
>     npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\hasee\\\\.electron-gyp\\\\20.2.0\\\\<(target_arch)\\\\node.lib',
>     npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\hasee\\Desktop\\Background3D\\Bg3d\\node_modules\\_ffi-napi@4.0.3@ffi-napi',
>     npm ERR! gyp info spawn args   '-Dnode_engine=v8',
>     npm ERR! gyp info spawn args   '--depth=.',
>     npm ERR! gyp info spawn args   '--no-parallel',
>     npm ERR! gyp info spawn args   '--generator-output',
>     npm ERR! gyp info spawn args   'C:\\Users\\hasee\\Desktop\\Background3D\\Bg3d\\node_modules\\_ffi-napi@4.0.3@ffi-napi\\build',
>     npm ERR! gyp info spawn args   '-Goutput_dir=.'
>     npm ERR! gyp info spawn args ]
>     npm ERR! gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
>     npm ERR! gyp info spawn args [
>     npm ERR! gyp info spawn args   'build/binding.sln',
>     npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
>     npm ERR! gyp info spawn args   '/nologo',
>     npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
>     npm ERR! gyp info spawn args ]
>     npm ERR! gyp ERR! build error
>     npm ERR! gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
>     npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\hasee\AppData\Roaming\nvm\v16.17.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
>     npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
>     npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
>     npm ERR! gyp ERR! System Windows_NT 10.0.19044
>     npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hasee\\AppData\\Roaming\\nvm\\v16.17.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
>     npm ERR! gyp ERR! cwd C:\Users\hasee\Desktop\Background3D\Bg3d\node_modules\_ffi-napi@4.0.3@ffi-napi
>     npm ERR! gyp ERR! node -v v16.17.0
>     npm ERR! gyp ERR! node-gyp -v v9.0.0
>     npm ERR! gyp ERR! not ok
> 
>     npm ERR! A complete log of this run can be found in:
>     npm ERR!     E:\Program Files\nodejs\node_cache\_logs\2022-09-24T12_17_26_056Z-debug-0.log
> 
>                     command='C:\Program Files\nodejs\node.exe' 'C:\Users\hasee\AppData\Roaming\nvm\v16.17.0\node_modules\npm\bin\npm-cli.js' rebuild ffi-napi@4.0.3 ref-napi@3.0.3 ref-napi@3.0.3
>                     workingDir=
> ```

have you managed to resolve this issue? I got the same one

**Comment by cclauss** [comment]
> npm ERR! gyp ERR! node-gyp -v v9.0.0

Please retry with a current version of `node-gyp`.
* https://github.com/nodejs/node-gyp/releases

**Comment by Chrys4lisfag** [comment]
```
yarn add ffi-napi
info No lockfile found.
[1/4] Resolving packages...
⠁ (node:46328) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[2/2] ⢀ ffi-napi
error C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi
Output:
C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@21.2.0 | win32 | x64
gyp info find Python using Python version 3.12.0 found at "C:\Python312\python.exe"

gyp info find VS using VS2022 (17.8.34316.72) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Professional"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python312\python.exe
gyp info spawn args [
gyp info spawn args 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'msvs',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Users\\koval\\Desktop\\ffi yarn\\node_modules\\ffi-napi\\build\\config.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args '-I',
gyp info spawn args 'C:\\Users\\koval\\AppData\\Local\\node-gyp\\Cache\\21.2.0\\include\\node\\common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=C:\\Users\\koval\\AppData\\Local\\node-gyp\\Cache\\21.2.0',
gyp info spawn args '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\koval\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\21.2.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args '-Dmodule_root_dir=C:\\Users\\koval\\Desktop\\ffi yarn\\node_modules\\ffi-napi',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'C:\\Users\\koval\\Desktop\\ffi yarn\\node_modules\\ffi-napi\\build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args 'build\\binding.sln',
gyp info spawn args '/clp:Verbosity=minimal',
gyp info spawn args '/nologo',
gyp info spawn args '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]

  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi\build\Release\\nothing.lib
  Preprocessing assembly file ..\..\..\deps\libffi\src\x86\win64_intel.preasm
  ""call"" �� ���� ����७��� ��� ���譥�
  ��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi\build\deps\libffi\ffi.targets(34,5): error MSB3721: ��室 �� ������� "call "call" "../../../deps/libffi/preprocess_asm.cmd" "../../../deps/libffi/include" "../../../deps/libffi/config/win/x64" "..\..\..\deps\libffi\src\x86\win64_intel.preasm" "Release\obj\ffi\win64_intel.asm"" � ����� "1". [C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi\build\deps\libffi\ffi.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
gyp ERR! stack at ChildProcess.emit (node:events:519:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi
gyp ERR! node -v v21.2.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok
```

**Comment by Chrys4lisfag** [comment]
same for npm
```
npm ERR! code 1
npm ERR! path C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! nothing.c
npm ERR!   win_delay_load_hook.cc
npm ERR!   nothing.vcxproj -> C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi\build\Release\\nothing.lib
npm ERR!   Preprocessing assembly file ..\..\..\deps\libffi\src\x86\win64_intel.preasm
npm ERR!   ""call"" �� ���� ����७��� ��� ���譥�
npm ERR!   ��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
npm ERR! C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi\build\deps\libffi\ffi.targets(34,5): error MSB3721: ��室 �� ������� "call "call" "../../../deps/libffi/preprocess_asm.cmd" "../../../deps/libffi/include" "../../../deps/libffi/config/win/x64" "..\..\..\deps\libffi\src\x86\win64_intel.preasm" "Release\obj\ffi\win64_intel.asm"" � ����� "1". [C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi\build\deps\libffi\ffi.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.2.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.0 found at "C:\Python312\python.exe"
npm ERR! gyp info find VS using VS2022 (17.8.34316.72) found at:
npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Professional"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python312\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'msvs',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Users\\koval\\Desktop\\ffi yarn\\node_modules\\ffi-napi\\build\\config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Users\\koval\\AppData\\Local\\node-gyp\\Cache\\21.2.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=C:\\Users\\koval\\AppData\\Local\\node-gyp\\Cache\\21.2.0',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\koval\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\21.2.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=C:\\Users\\koval\\Desktop\\ffi yarn\\node_modules\\ffi-napi',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'C:\\Users\\koval\\Desktop\\ffi yarn\\node_modules\\ffi-napi\\build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args 'build\\binding.sln',
npm ERR! gyp info spawn args '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args '/nologo',
npm ERR! gyp info spawn args '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:519:28)
npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi
npm ERR! gyp ERR! node -v v21.2.0
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\koval\AppData\Local\npm-cache\_logs\2023-11-26T17_37_39_260Z-debug-0.log
```

**Comment by cclauss** [comment]
> `C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi`

Space in the filename...  It is possible to rename `ffi yarn` --> `ffi_yarn` and try again?

**Comment by Chrys4lisfag** [comment]
> > `C:\Users\koval\Desktop\ffi yarn\node_modules\ffi-napi`
> 
> Space in the filename... It is possible to rename `ffi yarn` --> `ffi_yarn` and try again?

Randomly worked and now it works for the first time, next time I do "yarn add ffi-napi" where it is already installed and it throws.

I've tried on dedicated server and it works there perfectly with vs19. Maybe somehow related to vs22 pro version. Will make more tests
