### ISSUE TITLE
Fatal error on electron v21.0.0

### ISSUE THREAD

**Issue by yellow1234** [node-ffi-napi/node-ffi-napi#225]
electron v21.0.0 is out 2 days ago with chromium 106.0.5249.51
Now the V8 memory cage for external buffers are enabled by default

while requiring the module there is a fatal error

Fatal error in V8: v8_ArrayBuffer_NewBackingStore When the V8 Sandbox is enabled, ArrayBuffer backing stores must be allocated inside the sandbox address space. Please use an appropriate ArrayBuffer::Allocator to allocate these buffers.

**Comment by darakuneko** [comment]
I have the same problem.

**Comment by Elendiar** [comment]
Same too. Is there any information about this how to fix/refactor?

**Comment by eamon-sun** [comment]
I also encountered this problem. Downgraded the version of electron to 20.0.0 and it worked.

**Comment by Rafatcb** [comment]
Duplicate of https://github.com/node-ffi-napi/node-ffi-napi/issues/218

**Comment by mengxin-FE** [comment]
I have the same problem.

**Comment by zerob13** [comment]
I have the same problem.

**Comment by Tanimodori** [comment]
I have the same problem.

**Comment by dongjq123** [comment]
https://www.npmjs.com/package/@inigolabs/ffi-napi
A foreign function interface (FFI) for Node.js, N-API style, with "v8::ArrayBuffer::GetBackingStore" patch

**Comment by Elendiar** [comment]
> https://www.npmjs.com/package/@inigolabs/ffi-napi A foreign function interface (FFI) for Node.js, N-API style, with "v8::ArrayBuffer::GetBackingStore" patch

Still get error, i think because i also use _ref-struct-di_ and _ref-union-di_

**Comment by Laurent-Noudohounsi-Doctolib** [comment]
I have the same problem too. Any hope to see this error fixed? 🫤

**Comment by navelpluisje** [comment]
> I also encountered this problem. Downgraded the version of electron to 20.0.0 and it worked.

Also worked for me

**Comment by Elendiar** [comment]
> https://www.npmjs.com/package/@inigolabs/ffi-napi A foreign function interface (FFI) for Node.js, N-API style, with "v8::ArrayBuffer::GetBackingStore" patch

At least with `@inigolabs/ffi-napi` and `@inigolabs/ref-napi` i run my app with electron 22.0, but get exception on native call
`user32.EnumWindows(callback, 0);`
```
Unhandled Exception Error: TypeError: error setting return value - buf.writeUInt8 is not a function
    at Object.proxy [as EnumWindows] (C:\Users\user\Documents\code\taskbar-client\node_modules\@inigolabs\ffi-napi\lib\_foreign_function.js:61:14)
    at eval (webpack-internal:///./src/main/workers/winEventHook.js:130:8)
```
This happens in `@inigolabs/ref-napi/lib/ref.js` at `return buf.writeUInt8(val, offset || 0);`
```
types.uint8 = {
  size: exports.sizeof.uint8,
  indirection: 1,
  get: function get (buf, offset) {
    return buf.readUInt8(offset || 0);
  },
  set: function set (buf, offset, val) {
    if (typeof val === 'string') {
      val = val.charCodeAt(0);
    }
    return buf.writeUInt8(val, offset || 0);
  }
};
```
when callback return value. This callback in winapi is
```
BOOL CALLBACK EnumWindowsProc(
  _In_ HWND   hwnd,
  _In_ LPARAM lParam
);
```
```
const windowsProc = ffi.Callback(ref.types.bool, [HWND, LPARAM], (hwnd) => {
  if (hwnd >= 0 && isDesktopWindow(hwnd, true)) {
    parentPort.postMessage({ event: "enum-foreground", data: getWindowData(hwnd) });
  }
  return true; // continue enumerate
});
```
Okay, and this callback can be fixed if return not a bool (` return 1; // continue enumerate`), but integer 1/0 (also change ref.types.bool -> ref.types.int). So `user32.EnumWindows(windowsProc, 0);` issue solved, now i have issue that `SetWinEventHook` callback not working... UPD: Fix this also with changing callback in-type. I found out by manual debugging with file-logger (because console.log wont work in worker with callback) try-catch exception in the types.uint32/* getter-setters of the @inigolabs fork source code :(

Also both `@inigolabs/*-napi` were updated and i got an issue with them, they wont build with error `@inigolabs\ref-napi: Command failed. Exit code: 2 Command: PYTHON=python3 node-gyp-build`. And changing dependencies versions doesnt help, until you set _resolutions_ in package.json (if use yarn, or _overrides_ if npm). Because `@inigolabs\ref-napi` inside, in own _node_modules_ have downloaded latest version of `@inigolabs/ref-napi`, that have issue with building too.
```
"resolutions": {
    "@inigolabs/ref-napi": "4.0.4"
  },
```
So despite some problems with type mismatch in callbacks with this fork, I still **got my application working with ffi and electron 22.**

**Comment by ericpromislow** [comment]
I can't install the `@inigolabs` patch on Windows because of the change in `package.json` from `"install": "node-gyp-build",` to `"install": "PYTHON=python3 node-gyp-build",`.  

Running `npm install` => error message `PYTHON: can't open file 'C:\\Users\\...node_modules\\@inigolabs\\ffi-napi\\=python3: No such file or directory`

Where does the `@inigolabs` code live anyway? Only at https://www.npmjs.com/package/@inigolabs/ffi-napi?activeTab=explore ? Meaning there's no way to file a bug and/or PR?

**Comment by Elendiar** [comment]
> I can't install the `@inigolabs`

in package.json set previous versions and install with yarn (or npm, but change `resolutions` to `overrides`)

```
"dependencies": {
    "@inigolabs/ffi-napi": "4.0.7",
    "@inigolabs/ref-napi": "4.0.4",
},
"resolutions": {
    "@inigolabs/ref-napi": "4.0.4"
  },
```

**Comment by inthegarage** [comment]
@Elendiar I'm not sure how that is going to fix the error as for me this still remains:

PYTHON: can't open file 'D:\\Work\\electron\\node_modules\\@inigolabs\\ref-napi\\=python3': [Errno 2] No such file or directory

It would seem the install part is not running correctly, however if I run the cmd file in the bindings all is ok.

@ericpromislow Your error may be due to the fact it that you've not "ln" the python command to python3, however you will still get my error above. Would appreciate some resolution on this as this library can't be installed 100% of the time right now.

I'm using the latest 4.0.10 version, without any resolution/overrides blocks - they didn't seem to work anyway.

**Comment by Elendiar** [comment]
@inthegarage 
You use yarn or npm? Try that with yarn, using in deps ` "@inigolabs/ffi-napi": "4.0.7", "@inigolabs/ref-napi": "4.0.4",` and in resolutions `"@inigolabs/ref-napi": "4.0.4"`.
`Resolutions` mean lock to this version, and if `ffi-napi` inside depends on `ref-napi ^6`, yarn anyway download `ref-napi 4.0.4` version.
This works.

**Comment by inthegarage** [comment]
@Elendiar 
I use Yarn on Windows, I tried this and it didn't work. In the install I see this:

`    "install": "PYTHON=python3 node-gyp-build",`

However that won't work as there are no bindings file in that folder, however running the node_modules\\.bin\\node-gyp-build.cmd does work without further issues as all files can be found.

In other words the problem isn't to do with versions or resolutions, the command simply cannot work in its current state. I don't know what the intention was, so I'm not sure I can provide a PR, but the solution would be to call the appropriate cmd file, rather than the python command.

**Comment by Elendiar** [comment]
@inthegarage Yes, this happens on latest version. Just use 4.0.7, it works.

**Comment by inthegarage** [comment]
@Elendiar That has worked, do you know how to raise an issue for the @inigolabs version there doesn't seem to be a github repo at-all for it.

**Comment by Ruslan-AER** [comment]
i tried this
```
"dependencies": {
    "@inigolabs/ffi-napi": "4.0.7",
    "@inigolabs/ref-napi": "4.0.4",
},
"overrides": {
    "@inigolabs/ref-napi": "4.0.4"
  },
```
i get this isusse when using 4.0.7
```
  ⨯ C:\Program Files\nodejs\node.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
Error output:
npm WARN config production Use `--omit=dev` instead.
npm WARN using --force Recommended protections disabled.
npm ERR! code 1
npm ERR! path C:\Users\Wasabi\Desktop\electron-react-boilerplate-main\release\app\node_modules\@inigolabs\ref-napi
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!   nothing.c
npm ERR! C:\Users\Wasabi\Desktop\electron-react-boilerplate-main\release\app\node_modules\node-addon-api\nothing.c : fatal error C1083: Cannot open compiler generated file: 'C:\Users\Wasabi\Desktop\electron-react-boilerplate-main\release\app\node_modules\@inigolabs\node-addon-api\Release\obj\nothing\node-addon-api\nothing.obj': Permission denied [C:\Users\Wasabi\Desktop\electron-react-boilerplate-main\release\app\node_modules\@inigolabs\node-addon-api\nothing.vcxproj]
npm ERR! FileTracker : error FTK1011: could not create the new file tracking log file: C:\Users\Wasabi\Desktop\electron-react-boilerplate-main\release\app\node_modules\@inigolabs\node-addon-api\Release\obj\nothing\nothing.tlog\CL.write.1.tlog. The file exists. [C:\Users\Wasabi\Desktop\electron-react-boilerplate-main\release\app\node_modules\@inigolabs\node-addon-api\nothing.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.14.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.8.3 found at "C:\Python38\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.33130.400) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python38\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\Wasabi\\Desktop\\electron-react-boilerplate-main\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Wasabi\\Desktop\\electron-react-boilerplate-main\\release\\app\\node_modules\\@inigolabs\\ref-napi\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Wasabi\\Desktop\\electron-react-boilerplate-main\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Wasabi\\.electron-gyp\\22.2.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Wasabi\\.electron-gyp\\22.2.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Wasabi\\Desktop\\electron-react-boilerplate-main\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Wasabi\\\\.electron-gyp\\\\22.2.1\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Wasabi\\Desktop\\electron-react-boilerplate-main\\release\\app\\node_modules\\@inigolabs\\ref-napi',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\Wasabi\\Desktop\\electron-react-boilerplate-main\\release\\app\\node_modules\\@inigolabs\\ref-napi\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\Wasabi\Desktop\electron-react-boilerplate-main\node_modules\node-gyp\lib\build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Wasabi\\Desktop\\electron-react-boilerplate-main\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Wasabi\Desktop\electron-react-boilerplate-main\release\app\node_modules\@inigolabs\ref-napi
npm ERR! gyp ERR! node -v v18.14.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Wasabi\AppData\Local\npm-cache\_logs\2023-02-13T15_10_58_576Z-debug-0.log
  failedTask=installAppDeps stackTrace=Error: C:\Program Files\nodejs\node.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
```



i get this issue when using 4.0.10.

```

  ⨯ C:\Program Files\nodejs\node.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
Error output:
npm WARN config production Use `--omit=dev` instead.
npm WARN using --force Recommended protections disabled.
npm ERR! code 1
npm ERR! path C:\Users\Wasabi\Desktop\electron-react-boilerplate-main\release\app\node_modules\@inigolabs\ffi-napi
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c PYTHON=python3 node-gyp-build
npm ERR! File "C:\Python38\lib\site.py", line 178
npm ERR!     file=sys.stderr)
npm ERR!         ^
npm ERR! SyntaxError: invalid syntax

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Wasabi\AppData\Local\npm-cache\_logs\2023-02-13T15_07_23_264Z-debug-0.log
  failedTask=installAppDeps stackTrace=Error: C:\Program Files\nodejs\node.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
```

**Comment by lwahonen** [comment]
> i get this isusse when using 4.0.7

Try running npm install repeatedly a few times.

**Comment by Ruslan-AER** [comment]
i get this now
```
npm ERR! File "C:\Python310\lib\site.py", line 93
npm ERR!     print(message, file=sys.stderr)
npm ERR!                        ^
npm ERR! SyntaxError: invalid syntax
```

while using 
Electron 22.2.1
switched to node 16.17.1
```
  "dependencies": {
    "@inigolabs/ffi-napi": "4.0.7",
    "usb-detection": "^4.14.1"
  },
  "devDependencies": {
    "@electron/rebuild": "^3.2.9"
  }
}
```

**Comment by inthegarage** [comment]
I found the error could be ignored. Not ideal and needs fixing.

**Comment by Ruslan-AER** [comment]
what are the effects of ignoring the error? how will it affect the packaged app

**Comment by inthegarage** [comment]
I didn't find any, my specific error was that original ffi-napi seg-faulted with electron +19, the ffi-napi library has not been updated for 2 years and electron I believe does 1/2 yearly releases -which makes sense as it's on 23 already.
Once I swapped to @inigolabs version I got the syserr, everything built and ran for my use-case however, I just ignored what is a post-install issue with yarn.

**Comment by Ruslan-AER** [comment]
i see, in my case it didn't work, and it didn't install ffi napi, I'll just keep using electron 18 or 19 for now until there is a solution.
and Thank you

**Comment by evakratalov** [comment]
i get this error:
Error: External buffers are not allowed
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)

while using:
Electron 25.2.0
"dependencies": {
    "@inigolabs/ffi-napi": "4.0.7",
    "@inigolabs/ref-napi": "4.0.4",
},
"overrides": {
    "@inigolabs/ref-napi": "4.0.4"
},

**Comment by inthegarage** [comment]
@evakratalov I suspect it doesn't work with Electron 25, perhaps downgrade to Electron 23, or migrate away from the tool altogether - which is what is in our backlog.
