### ISSUE TITLE
[BUG (package unusable)] `ENOENT` after ffi-napi intentionally deviates from given parameters

### ISSUE THREAD

**Issue by WillsterJohnson** [node-ffi-napi/node-ffi-napi#240]
I have a compiled lib in the file `<project root>/lib`, and a JS file attempting to use it at `scripts/lib.js`.

ffi-napi is adding `.so` to the file path I give it. If there was a `.so` extension, I would have added it to the path myself. However there isn't, so I didn't; the file is called `lib`, not `lib.so`.

Code and output below.

### `lib.js`

```js
import { Library } from "ffi-napi";
import path from "node:path";
import url from "node:url";

/** @type {import("./lib").SkMono} */
export const lib = Library(
  path.join(url.fileURLToPath(path.dirname(import.meta.url)), "..", "lib"), // NOTE: there is no `.so` here!!! (tested with `fs` - this file *does* exist)
  {
    fibonacci: ["int", ["int"]],
  },
);
```

### Output

```
node:fs:592
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/home/will/Desktop/github/sk-mono/lib.so'
    at Object.openSync (node:fs:592:3)
    at readFileSync (node:fs:460:35)
    at new DynamicLibrary (/home/will/Desktop/github/sk-mono/node_modules/.pnpm/ffi-napi@4.0.3/node_modules/ffi-napi/lib/dynamic_library.js:68:23)
    at Library (/home/will/Desktop/github/sk-mono/node_modules/.pnpm/ffi-napi@4.0.3/node_modules/ffi-napi/lib/library.js:47:10)
    at file:///home/will/Desktop/github/sk-mono/scripts/lib.js:6:23
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:518:24)
    at async loadESM (node:internal/process/esm_loader:102:5)
    at async handleMainPromise (node:internal/modules/run_main:66:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/will/Desktop/github/sk-mono/lib.so'
}
```

## Expected behaviour

ffi-napi will load the file I told it to, and `lib.js` should have no output currently.

## Actual behaviour

ffi-napi refuses to load the file I told it to and instead modifies the path I gave it. *Obviously* the path I gave it was correct, therefore the path it created after modifying is invalid, so it causes itself to crash after being given valid parameters.

### Importance

I cannot use this library without this being fixed.

**Comment by Pomax** [comment]
driveby comment: why does it not have a .so extension? This is for loading .dll files on windows, and .so files on linux/unix. So if your file has no .so extension, it's... not a .so file? Just rename it if it actually is?
