### ISSUE TITLE
not a valid Win32 application

### ISSUE THREAD

**Issue by andyin9** [node-ffi-napi/node-ffi-napi#242]
To build app for Windows on Linux CentOS 7 by using electronuserland/builder:wine image.

The packaged exe file can be installed successfully, but the application startup reports an error and the error description:

A JavaScript error occurred in the main process Uncaught Exception:Error:? C:\Users ...\AppData Loc... 26f0978b-dd24-4534-a6e6-7135af017806.tmp.node is not a valid Win32 application.? C: Users...\AppData Loc... 26f0978b-dd24-4534-ae6-7135af017806.tmp.nodeat process.func (as dlopen] (electron/is2c/asar bundle.js:5:1846)at Object.Module. extensions..node (internal/modules/cis/loader.js:1138:18)at Object.func [as .node] (electron/js2c/asar bundlejs:5:2073)at Module.load (internal/modules/cjs/loaderjs:935:32)at Module. load (internal/modules/cis/loader.js:776:14)at Function.f. load (electron/is2c/asar bundlejs:5:12913)at Module.require (internal/modules/cjs/loaderjs:959:19at require (internal/modules/cis/helpers.is:88:18)at load (C:\Program Files(App\resources app.asar node modules node-gyp-build index,js:22... at Object.canonymous>(C: Program Files\App\resources app.asar\node modules ffi-napi lib bindings.js:8:43)

**Comment by anyaoqi** [comment]
你的问题解决了吗
