### ISSUE TITLE
error when just require('ffi-napi');node version 18.16.0;electron 25.0.0

### ISSUE THREAD

**Issue by SunnyTian** [node-ffi-napi/node-ffi-napi#250]
![image](https://github.com/node-ffi-napi/node-ffi-napi/assets/17664209/5d29a73a-65f6-4021-af90-c1163e9d865d)

App threw an error during load
Error: Error in native callback
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at load (D:\projects\electron_proj\hairdry\node_modules\node-gyp-build\node-gyp-build.js:22:10)
    at Object.<anonymous> (**\node_modules\ref-napi\lib\ref.js:8:53)

**Comment by SunnyTian** [comment]
downgrade electron to 20.0.0

**Comment by kp-bang** [comment]
这样的话，就不能在最新的vscode插件里面使用了

**Comment by cclauss** [comment]
> In this case, it cannot be used in the latest vscode plug-in

* #269
