### ISSUE TITLE
Can’t install node-gyp 9 on Python 3.12

### ISSUE THREAD

**Issue by JuanDa237** [node-ffi-napi/node-ffi-napi#266]
I have install python and  "Desktop development with C++" workload as required in [node-gyp](https://www.npmjs.com/package/node-gyp), when i run `npm i node-gyp` i have no problem but when i install ffi-napi i get the following error:

```
npm ERR! code 1
npm ERR! path C:\Users\juan\Desktop\pos\test-print-escpos\node_modules\ffi-napi
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.15.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.1 found at "C:\Users\juan\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe"    
npm ERR! gyp info find VS using VS2022 (17.5.33502.453) found at:
npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\juan\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\juan\\AppData\\Roaming\\nvm\\v18.15.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\juan\\Desktop\\pos\\test-print-escpos\\node_modules\\ffi-napi\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\juan\\AppData\\Roaming\\nvm\\v18.15.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\juan\\AppData\\Local\\node-gyp\\Cache\\18.15.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\juan\\AppData\\Local\\node-gyp\\Cache\\18.15.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\juan\\AppData\\Roaming\\nvm\\v18.15.0\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\juan\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.15.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\juan\\Desktop\\pos\\test-print-escpos\\node_modules\\ffi-napi',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\juan\\Desktop\\pos\\test-print-escpos\\node_modules\\ffi-napi\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Users\juan\AppData\Roaming\nvm\v18.15.0\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "C:\Users\juan\AppData\Roaming\nvm\v18.15.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "C:\Users\juan\AppData\Roaming\nvm\v18.15.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\juan\AppData\Roaming\nvm\v18.15.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\juan\\AppData\\Roaming\\nvm\\v18.15.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\juan\Desktop\pos\test-print-escpos\node_modules\ffi-napi
npm ERR! gyp ERR! node -v v18.15.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
```

**Comment by cclauss** [comment]
> npm ERR! gyp ERR! node-gyp -v v9.3.1

Python 3.12 requires a node-gyp >= v10 that contains
* https://github.com/nodejs/gyp-next/pull/214

Please change the title of this issue to `Can’t install node-gyp 9 on Python 3.12` to help others find this info and then close the issue.

**Comment by JuanDa237** [comment]
Thanks, it is correct.
