### ISSUE TITLE
command failed. errno: -4071 (for all node x86 versions)

### ISSUE THREAD

**Issue by leo33853870** [node-ffi-napi/node-ffi-napi#271]
It's strange that ,  I installed ffi-napi seccessfully several months ago . 
but now , it does not work.

And It is OK to install ffi-napi with nodejs x64.    No error occurs.

But when I install ffi-napi with Node x86 (for example, 18.20.2 lts , or 20.12.2 lts), it failed . 

`C:\test\tmp>npm install ffi-napi
npm ERR! code 1
npm ERR! path C:\test\tmp\node_modules\ffi-napi
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! node:internal/child_process:421
npm ERR!     throw new ErrnoException(err, 'spawn');
npm ERR!     ^
npm ERR!
npm ERR! Error: spawn EINVAL
npm ERR!     at ChildProcess.spawn (node:internal/child_process:421:11)
npm ERR!     at Object.spawn (node:child_process:761:9)
npm ERR!     at build (C:\test\tmp\node_modules\node-gyp-build\bin.js:30:8)
npm ERR!     at preinstall (C:\test\tmp\node_modules\node-gyp-build\bin.js:39:32)
npm ERR!     at C:\test\tmp\node_modules\node-gyp-build\bin.js:11:7
npm ERR!     at ChildProcess.exithandler (node:child_process:430:5)
npm ERR!     at ChildProcess.emit (node:events:518:28)
npm ERR!     at maybeClose (node:internal/child_process:1105:16)
npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
npm ERR!   errno: -4071,
npm ERR!   code: 'EINVAL',
npm ERR!   syscall: 'spawn'
npm ERR! }
npm ERR!
npm ERR! Node.js v20.12.2

npm ERR! A complete log of this run can be found in: C:\Users\leo33\AppData\Local\npm-cache\_logs\2024-04-27T23_50_34_748Z-debug-0.log`

When I installed nodejs , I checked chocolatey option
![check](https://github.com/node-ffi-napi/node-ffi-napi/assets/99707650/c01358e9-a3d8-44ef-a43a-f5af3294ca97)

**Comment by cclauss** [comment]
Duplicate of
* #269
