### ISSUE TITLE
ERR_BUFFER_OUT_OF_BOUNDS   Check failed: result.second.

### ISSUE THREAD

**Issue by Liguangwei0321** [node-ffi-napi/node-ffi-napi#276]
using napi to call c++：errors display

Calling YUS_DLL_SendHeartBeat with camHandle: 548285038608
Error sending HeartBeat response: Error: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at Object.proxy [as YUS_DLL_SendHeartBeat] (/home/linaro/webprj/multiband/node_modules/ffi-napi/lib/_foreign_function.js:61:14)
    at /home/linaro/webprj/multiband/server.js:47:40
    at Object.<anonymous> (/home/linaro/webprj/multiband/node_modules/ffi-napi/lib/callback.js:66:27)
    at Object.proxy [as YUS_DLL_ProtocolParse] (/home/linaro/webprj/multiband/node_modules/ffi-napi/lib/_foreign_function.js:61:14)
    at Socket.<anonymous> (/home/linaro/webprj/multiband/server.js:195:29)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
YUS_DLL_ProtocolParse 1
Server Received command: aa2300950305000000f2ff4344313130323341343034000002311607000000c586d823

#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ff9ced2f0
 1: 0xa9263c  [node]
 2: 0x18fb260 V8_Fatal(char const*, ...) [node]
 3: 0xe504fc v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xbbf284 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0x9ee80c napi_get_typedarray_info [node]
 6: 0x7fa86a6230  [/home/linaro/webprj/multiband/node_modules/ref-struct-napi/node_modules/ref-napi/build/Release/binding.node]
 7: 0x7fa86ab510 Napi::details::CallbackData<Napi::Value (*)(Napi::CallbackInfo const&), Napi::Value>::Wrapper(napi_env__*, napi_callback_info__*) [/home/linaro/webprj/multiband/node_modules/ref-struct-napi/node_modules/ref-napi/build/Release/binding.node]
 8: 0x9e623c  [node]
 9: 0xbfdaa4  [node]
10: 0xbfeb68  [node]
11: 0xbff1e8 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x139ef4c  [node]
追踪与中断点陷阱

**Comment by cclauss** [comment]
Duplicate of
* #269
