### ISSUE TITLE
Getting error during rebuild "node-ffi-napi" - Error: spawn EINVAL

### ISSUE THREAD

**Issue by dhaka2071** [node-ffi-napi/node-ffi-napi#287]
node:internal/child_process:420
    throw new ErrnoException(err, 'spawn');
    ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at Object.spawn (node:child_process:753:9)
    at build (C:\test-project\node_modules\node-ffi-napi\node_modules\node-gyp-build\bin.js:29:8)
    at preinstall (C:\test-project\node_modules\node-ffi-napi\node_modules\node-gyp-build\bin.js:38:32)
    at C:\test-project\node_modules\node-ffi-napi\node_modules\node-gyp-build\bin.js:11:7
    at ChildProcess.exithandler (node:child_process:421:5)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:524:28) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

Node.js v22.12.0
npm error code 1
npm error path C:\test-project\node_modules\node-ffi-napi
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build

Could you please help me with the above issues? 

Node Version: 22.12.0
node-gyp Version: 11.0.0
npm version: 10.9.0

**Comment by cclauss** [comment]
Duplicate of
* #269
