### ISSUE TITLE
Callbacks not working

### ISSUE THREAD

**Issue by Sorunome** [node-ffi-napi/node-ffi-napi#52]
When migrating a library from ffi over to ffi-napi it seems that callbacks aren't working: they cause a segmentation fault. Using ffi-napi 2.4.6

This is the relevant backtrace with gdb:

```
(gdb) bt
#0  0x00007ffff7f99bfb in ffi_closure_unix64_inner ()
   from /home/sorunome/repos/js-toxcore-c/node_modules/ffi-napi/build/Release/ffi_bindings.node
#1  0x00007ffff7f9a232 in ffi_closure_unix64 ()
   from /home/sorunome/repos/js-toxcore-c/node_modules/ffi-napi/build/Release/ffi_bindings.node
#2  0x00007ffff43fbb4c in tox_self_connection_status_handler (m=0x5555573f5bc0, connection_status=2, 
    user_data=0x7fffffffd020) at /home/sorunome/repos/c-toxcore/toxcore/tox.c:116  <-- This is where the library calls the callback
```

**Comment by addaleax** [comment]
Reopening because the fix is a regression in itself.
