### ISSUE TITLE
node-gyp rebuild failed on OSX 10.15 Catalina

### ISSUE THREAD

**Issue by guilhermeKodama** [node-ffi-napi/node-ffi-napi#53]
Node version: v10.18.1
Yarn version: 1.19.0
ProductName:	Mac OS X
ProductVersion:	10.15.2
BuildVersion:	19C57

It fails when I try to install with `yarn add ffi-napi`

Logs
```
yarn add ffi-napi
yarn add v1.19.0
$ node ./internals/scripts/CheckYarn.js
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-final-form > ts-essentials@5.0.0" has unmet peer dependency "typescript@>=3.7.0".
warning " > react-hot-loader@4.12.18" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
warning " > eslint-config-airbnb@18.0.1" has unmet peer dependency "eslint-plugin-react-hooks@^1.7.0".
warning " > eslint-config-erb@0.1.1" has incorrect peer dependency "eslint@^5.12.0".
warning " > eslint-config-erb@0.1.1" has incorrect peer dependency "eslint-formatter-pretty@^2.1.1".
warning " > eslint-config-erb@0.1.1" has incorrect peer dependency "eslint-plugin-compat@^2.7.0".
warning " > eslint-config-erb@0.1.1" has incorrect peer dependency "eslint-plugin-flowtype@^3.13.0".
warning " > eslint-config-erb@0.1.1" has incorrect peer dependency "eslint-plugin-jest@^22.16.0".
warning " > eslint-config-react-app@2.1.0" has incorrect peer dependency "babel-eslint@^7.2.3".
warning " > eslint-config-react-app@2.1.0" has incorrect peer dependency "eslint@^4.1.1".
warning " > eslint-config-react-app@2.1.0" has incorrect peer dependency "eslint-plugin-flowtype@^2.34.1".
warning " > eslint-config-react-app@2.1.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^5.1.1".
warning "eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] 🔨  Building fresh packages...
[6/15] ⠈ electron
[11/15] ⠈ ref-napi
[-/15] ⠈ waiting...
[-/15] ⠈ waiting...
error /Users/guilherme/Documents/Documents/Projects/Machine Learning/mee/SAT/app/node_modules/ref-napi: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/guilherme/Documents/Documents/Projects/Machine Learning/mee/SAT/app/node_modules/ref-napi
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@10.18.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [ '/Users/guilherme/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/guilherme/Documents/Documents/Projects/Machine Learning/mee/SAT/app/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/guilherme/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/guilherme/Library/Caches/node-gyp/10.18.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/guilherme/Library/Caches/node-gyp/10.18.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/guilherme/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/guilherme/Library/Caches/node-gyp/10.18.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/guilherme/Documents/Documents/Projects/Machine Learning/mee/SAT/app/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 30, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 45, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 248, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/nothing.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/guilherme/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/Users/guilherme/.nvm/versions/node/v10.18.1/bin/node" "/Users/guilherme/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/guilherme/Documents/Documents/Projects/Machine Learning/mee/SAT/app/node_modules/ref-napi
```

**Comment by addaleax** [comment]
That looks like a node-gyp bug, not one with this project. Maybe also try updating yarn, as that ships with a slightly outdated version of node-gyp?

**Comment by alexeykovalev** [comment]
@guilhermeKodama
you have a wrong path to the `libtool` - GNU's one is confused with XCode's toolchain tool (probably you did install it previously with Homebrew) 

please take a look at the comment below to solve your issue 
https://github.com/nodejs/node/issues/2341#issuecomment-456359181

cc: addaleax

**Comment by cakoose** [comment]
I think this is the issue:
1. ffi-napi uses the globally-installed "node-gyp" (instead of specifying it as a dependency).
2. For example, I'm using the latest Node 12 (12.16.1), which includes node-gyp 5.0.5 in the global "node_modules".
3. That version of node-gyp is missing [some fixes](https://github.com/nodejs/node-gyp/commit/9f4f0fa34e139be3e21c5e4a27bbcb4a45625b0b) to make it work on Python 3.
    - The specific line that is relevant to the above stack trace: [link](https://github.com/nodejs/node-gyp/commit/9f4f0fa34e139be3e21c5e4a27bbcb4a45625b0b#diff-a486ea7ed25fd07c6c5a3aee31ed8308R249).
4. On some people's machines, `python` refers to Python 3, which will become more and more common going forward.  On those machines, the build fails.

I think this can be fixed by adding an explicit dependency on "node-gyp", instead of picking up whatever is globally installed.  I don't have much experience with gyp, so I'm not sure whether this has downsides, but:
1. I modified ffi-napi's "package.json" and added dependency on node-gyp v5.1.1.  That seemed to fix the issue.
2. A bunch of packages seem to do this: ["828 Dependents"](https://www.npmjs.com/package/node-gyp?activeTab=dependents).
3. Part of what makes this kind of issue difficult to track down is that people have different versions of node-gyp installed.  Locking down the version number would get rid of that variable.

**Comment by gino8080** [comment]
> I think this is the issue:
> 
> 1. ffi-napi uses the globally-installed "node-gyp" (instead of specifying it as a dependency).
> 2. For example, I'm using the latest Node 12 (12.16.1), which includes node-gyp 5.0.5 in the global "node_modules".
> 3. That version of node-gyp is missing [some fixes](https://github.com/nodejs/node-gyp/commit/9f4f0fa34e139be3e21c5e4a27bbcb4a45625b0b) to make it work on Python 3.
>    
>    * The specific line that is relevant to the above stack trace: [link](https://github.com/nodejs/node-gyp/commit/9f4f0fa34e139be3e21c5e4a27bbcb4a45625b0b#diff-a486ea7ed25fd07c6c5a3aee31ed8308R249).
> 4. On some people's machines, `python` refers to Python 3, which will become more and more common going forward.  On those machines, the build fails.
> 
> I think this can be fixed by adding an explicit dependency on "node-gyp", instead of picking up whatever is globally installed. I don't have much experience with gyp, so I'm not sure whether this has downsides, but:
> 
> 1. I modified ffi-napi's "package.json" and added dependency on node-gyp v5.1.1.  That seemed to fix the issue.
> 2. A bunch of packages seem to do this: ["828 Dependents"](https://www.npmjs.com/package/node-gyp?activeTab=dependents).
> 3. Part of what makes this kind of issue difficult to track down is that people have different versions of node-gyp installed.  Locking down the version number would get rid of that variable.

Thank you @cakoose , manually updating to 5.1.1 (npm i node-gyp inside global node_modules) fixes the issue for me!
