### ISSUE TITLE
ffi-napi 2.5.0 crashes on Node 14 on macOS 10.15.4

### ISSUE THREAD

**Issue by nsabovic** [node-ffi-napi/node-ffi-napi#71]
In an empty directory:

```
projects/test/testffi ❯ npm i ffi-napi

...

projects/test/testffi took 11s ❯ node
Welcome to Node.js v14.0.0.
Type ".help" for more information.
> os.version()
'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64'

> require('ffi-napi')


#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffeefbf3330
 1: 0x1000d5142 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/usr/local/bin/node]
 2: 0x100a18c31 V8_Fatal(char const*, ...) [/usr/local/bin/node]
 3: 0x100378436 v8::internal::GlobalBackingStoreRegistry::Register(std::__1::shared_ptr<v8::internal::BackingStore>) [/usr/local/bin/node]
 4: 0x10018d9e7 v8::ArrayBuffer::GetBackingStore() [/usr/local/bin/node]
 5: 0x100063174 node::Buffer::New(node::Environment*, char*, unsigned long, void (*)(char*, void*), void*) [/usr/local/bin/node]
 6: 0x100062f0b node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/usr/local/bin/node]
 7: 0x10005ea05 napi_create_external_buffer [/usr/local/bin/node]
 8: 0x10418c99e Napi::Buffer<char> Napi::Buffer<char>::New<Napi::Value FFI::WrapPointer<_ffi_type>(Napi::Env, _ffi_type*, unsigned long)::'lambda'(Napi::Env, char*)>(napi_env__*, char*, unsigned long, _ffi_type) [/Users/nsabovic/projects/test/testffi/node_modules/ffi-napi/build/Release/ffi_bindings.node]
 9: 0x10418742b FFI::FFI::InitializeBindings(Napi::Env, Napi::Object) [/Users/nsabovic/projects/test/testffi/node_modules/ffi-napi/build/Release/ffi_bindings.node]
10: 0x10418b2a3 __napi_Init(napi_env__*, napi_value__*) [/Users/nsabovic/projects/test/testffi/node_modules/ffi-napi/build/Release/ffi_bindings.node]
11: 0x10005e048 napi_module_register_by_symbol(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, napi_value__* (*)(napi_env__*, napi_value__*)) [/usr/local/bin/node]
12: 0x100061e83 std::__1::__function::__func<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0, std::__1::allocator<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0>, bool (node::binding::DLib*)>::operator()(node::binding::DLib*&&) [/usr/local/bin/node]
13: 0x100061034 node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
14: 0x1001cd7ea v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
15: 0x1001cce74 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
16: 0x1001cc698 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
17: 0x10074fe79 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
zsh: illegal hardware instruction  node
```

**Comment by vweevers** [comment]
Could be due to the prebuilt binary being built on a newer osx/xcode (cc @pimterry).

Could you try `npm i --build-from-source`?

**Comment by nsabovic** [comment]
Exactly the same result. Started with an empty directory, and built it from source.  FYI, I have Xcode 11.4.1 installed.

**Comment by nsabovic** [comment]
I have tried it with node 14.0.0 (from Homebrew), and it doesn't work. node 13.13.0 worked. Also tried nvm, same story, 13.13.0 works but 14.0.0 does not.

**Comment by nsabovic** [comment]
If I were a betting man, I'd wager this had something to do with it:

https://github.com/nodejs/node/pull/30782

In the thread, they also mention the same crash in deps/v8/src/objects/backing-store.cc.

**Comment by addaleax** [comment]
Yes – this is a known bug, and not easily addressable without major changes. https://github.com/node-ffi-napi/node-ffi-napi/pull/68 would take care of this, but it’ll definitely take so more time to work out everything there.

**Comment by hjlld** [comment]
same error but on Windows 10 1903 with Node.js 14.0.0

```

#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 00000018871E93D0
 1: 00007FF64B93AB0F v8::internal::wasm::DisjointAllocationPool::~DisjointAllocationPool+74383
 2: 00007FF64B874D7F std::basic_ostream<char,std::char_traits<char> >::operator<<+55439
 3: 00007FF64C43BB22 V8_Fatal+162
 4: 00007FF64BF04C6D v8::internal::BackingStore::Reallocate+653
 5: 00007FF64C1303E9 v8::ArrayBuffer::GetBackingStore+137
 6: 00007FF64B900C68 v8::internal::Malloced::operator delete+15736
 7: 00007FF64B9056A5 node::Buffer::Length+1813
 8: 00007FF64B905D63 node::Buffer::New+163
 9: 00007FF64B90B586 napi_create_external_buffer+230
10: 00007FFA9244BFA9 FFI::WrapPointer<_ffi_type>+137 [D:\Code\KeRendererJS\node_modules\ffi-napi\src\ffi.h]:L37
11: 00007FFA924503D4 FFI::FFI::InitializeBindings+3668 [D:\Code\KeRendererJS\node_modules\ffi-napi\src\ffi.cc]:L117
12: 00007FFA9244F370 Init+64 [D:\Code\KeRendererJS\node_modules\ffi-napi\src\ffi.cc]:L304
13: 00007FFA9244BEFB Napi::details::WrapCallback<<lambda_8c7377a71108815b2eee34f099f4cb99> >+43 [D:\Code\KeRendererJS\node_modules\node-addon-api\napi-inl.h]:L104
14: 00007FFA9244A2CB __napi_Init+59 [D:\Code\KeRendererJS\node_modules\ffi-napi\src\ffi.cc]:L309
15: 00007FF64B90AA5B node_module_register+5851
16: 00007FF64B907D73 node::Buffer::New+7427
17: 00007FF64B908632 node::Buffer::New+9666
18: 00007FF64C0F371F v8::internal::Builtins::builtin_handle+330191
19: 00007FF64C0F2CAE v8::internal::Builtins::builtin_handle+327518
20: 00007FF64C0F2FA7 v8::internal::Builtins::builtin_handle+328279
21: 00007FF64C0F2DF3 v8::internal::Builtins::builtin_handle+327843
22: 00007FF64C1D0BFD v8::internal::SetupIsolateDelegate::SetupHeap+466093
23: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
24: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
25: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
26: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
27: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
28: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
29: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
30: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
31: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
32: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
33: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
34: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
35: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
36: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
37: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
38: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
39: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
40: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
41: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
42: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
43: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
44: 00007FF64C162939 v8::internal::SetupIsolateDelegate::SetupHeap+14825
45: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
46: 00007FF64C162939 v8::internal::SetupIsolateDelegate::SetupHeap+14825
47: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
48: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
49: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
50: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
51: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
52: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
53: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
54: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
55: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
56: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
57: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
58: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
59: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
60: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
61: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
62: 00007FF64C16697E v8::internal::SetupIsolateDelegate::SetupHeap+31278
63: 00007FF64C16656C v8::internal::SetupIsolateDelegate::SetupHeap+30236
64: 00007FF64C04A6CF v8::internal::Execution::CallWasm+1743
65: 00007FF64C049EDF v8::internal::Execution::Call+191
66: 00007FF64C123A87 v8::Function::Call+615
67: 00007FF64B7E6EDB std::basic_ostream<char,std::char_traits<char> >::put+45867
68: 00007FF64C0F371F v8::internal::Builtins::builtin_handle+330191
69: 00007FF64C0F2CAE v8::internal::Builtins::builtin_handle+327518
70: 00007FF64C0F2FA7 v8::internal::Builtins::builtin_handle+328279
71: 00007FF64C0F2DF3 v8::internal::Builtins::builtin_handle+327843
72: 00007FF64C1D0BFD v8::internal::SetupIsolateDelegate::SetupHeap+466093
73: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
74: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
75: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
76: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
77: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
78: 00007FF64C168D98 v8::internal::SetupIsolateDelegate::SetupHeap+40520
79: 00007FF64C16697E v8::internal::SetupIsolateDelegate::SetupHeap+31278
80: 00007FF64C16656C v8::internal::SetupIsolateDelegate::SetupHeap+30236
81: 00007FF64C04A6CF v8::internal::Execution::CallWasm+1743
82: 00007FF64C049EDF v8::internal::Execution::Call+191
83: 00007FF64C123A87 v8::Function::Call+615
84: 00007FF64B90CCFF napi_unref_threadsafe_function+2543
85: 00007FF64B910897 node::Start+1159
86: 00007FF64B910C91 node::Start+2177
87: 00007FF64B959AB8 node::LoadEnvironment+56
88: 00007FF64B89CCF3 EVP_CIPHER_CTX_buf_noconst+39939
89: 00007FF64B910530 node::Start+288
90: 00007FF64B7766FC RC4_options+339452
91: 00007FF64C684F1C v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+156812
92: 00007FFAD0AB7BD4 BaseThreadInitThunk+20
93: 00007FFAD18CCE51 RtlUserThreadStart+33
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by felipebalbi** [comment]
Same error on Linux

**Comment by felipebalbi** [comment]
This fails when running tests as well:

```
> yarn test
yarn run v1.22.4
$ node-gyp rebuild --directory test && nyc mocha -gc --reporter spec
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.1.0 | linux | x64
gyp info chdir test
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/balbi/workspace/node-ffi-napi/test/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/balbi/.cache/node-gyp/14.1.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/balbi/.cache/node-gyp/14.1.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/balbi/.cache/node-gyp/14.1.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/balbi/workspace/node-ffi-napi/test',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/balbi/workspace/node-ffi-napi/test/build'
  CC(target) Release/obj.target/nothing/../node_modules/node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node_modules/node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/ffi_tests/ffi_tests.o
  SOLINK_MODULE(target) Release/obj.target/ffi_tests.node
  COPY Release/ffi_tests.node
make: Leaving directory '/home/balbi/workspace/node-ffi-napi/test/build'
gyp info ok 


#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffdd8120250
 1: 0x560f686d5773  [/usr/bin/node]
 2: 0x560f69103488 V8_Fatal(char const*, ...) [/usr/bin/node]
 3: 0x560f68a9d5ff v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [/usr/bin/node]
 4: 0x560f6881a175 v8::ArrayBuffer::GetBackingStore() [/usr/bin/node]
 5: 0x560f6863d36c node::Buffer::New(node::Environment*, char*, unsigned long, void (*)(char*, void*), void*) [/usr/bin/node]
 6: 0x560f6863d660 node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/usr/bin/node]
 7: 0x560f6862ff41 napi_create_external_buffer [/usr/bin/node]
 8: 0x7f8ffa486617  [/home/balbi/workspace/node-ffi-napi/build/Release/ffi_bindings.node]
 9: 0x7f8ffa4897d2 FFI::FFI::InitializeBindings(Napi::Env, Napi::Object) [/home/balbi/workspace/node-ffi-napi/build/Release/ffi_bindings.node]
10: 0x7f8ffa489e40  [/home/balbi/workspace/node-ffi-napi/build/Release/ffi_bindings.node]
11: 0x7f8ffa4866f5 __napi_Init(napi_env__*, napi_value__*) [/home/balbi/workspace/node-ffi-napi/build/Release/ffi_bindings.node]
12: 0x560f686313d9 napi_module_register_by_symbol(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, napi_value__* (*)(napi_env__*, napi_value__*)) [/usr/bin/node]
13: 0x560f68632dd6  [/usr/bin/node]
14: 0x560f6863377c node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/bin/node]
15: 0x560f68848ae7 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/bin/node]
16: 0x560f68848eb1  [/usr/bin/node]
17: 0x560f6884976a  [/usr/bin/node]
18: 0x560f6884a086 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
19: 0x560f68fdac59  [/usr/bin/node]
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
error Command failed with signal "SIGILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by addaleax** [comment]
@hjlld @felipebalbi I’ve hidden your comments. I appreciate the interest, but as I said, this is a known bug, and it takes some work to figure out how to work around the problems that the V8 updates pose to us (and making sure that those are correct). You can try #68, and if you want, I can make a pre-release using that branch, but be aware that that’s *definitely* still broken.

**Comment by splitice** [comment]
This also occurs on Armv7 (Raspberry PI equivilent) Linux with Nodejs 14+

```
#0  0x009b426c in v8::base::OS::Abort() ()
#1  0x01797b78 in V8_Fatal(char const*, ...) ()
#2  0x00e26f1c in v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) ()
#3  0x00b7e1ac in v8::ArrayBuffer::GetBackingStore() ()
#4  0x00a14ff6 in node::Buffer::New(node::Environment*, char*, unsigned int, void (*)(char*, void*), void*) ()
#5  0x00a15368 in node::Buffer::New(v8::Isolate*, char*, unsigned int, void (*)(char*, void*), void*) ()
#6  0x00a0dcfc in napi_create_external_buffer ()
#7  0xb6449522 in Napi::Buffer<char> Napi::Buffer<char>::New<FFI::WrapPointer<_ffi_type>(Napi::Env, _ffi_type*, unsigned int)::{lambda(Napi::Env, char*)#1}>(napi_env__*, char*, unsigned int, FFI::WrapPointer<_ffi_type>(Napi::Env, _ffi_type*, unsigned int)::{lambda(Napi::Env, char*)#1}) [clone .constprop.70] ()
   from /usr/lib/node/nedb/node_modules/ffi-napi/build/Release/ffi_bindings.node
#8  0xb644c00c in FFI::FFI::InitializeBindings(Napi::Env, Napi::Object) () from /usr/lib/node/nedb/node_modules/ffi-napi/build/Release/ffi_bindings.node
#9  0xb644cec0 in Init(Napi::Env, Napi::Object) () from /usr/lib/node/nedb/node_modules/ffi-napi/build/Release/ffi_bindings.node
#10 0xb6449b6e in __napi_Init(napi_env__*, napi_value__*) () from /usr/lib/node/nedb/node_modules/ffi-napi/build/Release/ffi_bindings.node
#11 0x00a0d422 in napi_module_register_by_symbol(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, napi_value__* (*)(napi_env__*, napi_value__*)) ()
#12 0x00a0fbfa in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Backtrace is slightly different however. Very similar though.

**Comment by addaleax** [comment]
This should be fixed in ffi-napi@3.x

**Comment by Yongle-Fu** [comment]
this bug still exists on  ffi-napi 4.0.1

**Comment by rosek86** [comment]
Hello,

I have the same problem ffi-napi 4.0.2, tested on Node 14 and 15. This happens when a callback is executed:

```
const stdoutLogCallback = ffi.Callback('void', [ 'string' ], (msg) => {
  console.log('log:', msg);
});
```
